BEGIN
RAISE NOTICE 'INICIO DA TRANSAÇAO...';

DECLARE

X RECORD;

V_CPF VARCHAR:= '10627466788';
V_SEMESTRE VARCHAR:= '12016';
V_SEMESTRE_SEM_DESCONTO VARCHAR= '8712.72';
V_SEMESTRE_COM_DESCONTO VARCHAR = '8712.72';
V_SEMESTRE_ATUAL VARCHAR = '8712.72';
V_FINANCIADO_SEMESTRE VARCHAR;
V_FINANCIAMENTO_GLOBAL VARCHAR;
V_FINANCIAMENTO_EXERCICIO VARCHAR;
V_SEMESTRALIDADE_PARA_FIES VARCHAR = '8712.72';
SOMA_SEMESTRE VARCHAR;
V_LIMITE_GLOBAL VARCHAR;
V_SEMESTRE_COM_DESCONTO_CONTRATO VARCHAR;
RESULT BIGINT;

BEGIN


SELECT SUM(VL_FINANCIADO_SEMESTRE) INTO SOMA_SEMESTRE  FROM INSCRICAO.TB_FIES_ADITAMENTO WHERE NU_CPF = V_CPF AND CO_SITUACAO_ADITAMENTO = 49;
FOR X IN

SELECT *
FROM  INSCRICAO.TB_FIES_ADITAMENTO WHERE NU_CPF = V_CPF
AND CO_SITUACAO_ADITAMENTO = 49
ORDER BY CO_SEMESTRE_ADITAMENTO DESC LIMIT 1

LOOP
IF (X.CO_ADITAMENTO IS NOT NULL) THEN
V_FINANCIADO_SEMESTRE = V_SEMESTRE_ATUAL * (X.NU_PERCENT_SOLICITADO_FINANC /100);
SOMA_SEMESTRE = SOMA_SEMESTRE + V_FINANCIADO_SEMESTRE;
V_FINANCIAMENTO_EXERCICIO = V_SEMESTRE_COM_DESCONTO * (X.NU_PERCENT_SOLICITADO_FINANC /100);
V_FINANCIAMENTO_GLOBAL = X.QT_SEMESTRE_FINANCIAMENTO * V_FINANCIADO_SEMESTRE;
V_LIMITE_GLOBAL = V_FINANCIAMENTO_GLOBAL * 1.25;

IF(SOMA_SEMESTRE <= X.VL_LIMITE_GLOBAL) THEN
V_FINANCIAMENTO_GLOBAL = X.VL_FINANCIAMENTO_GLOBAL;
V_LIMITE_GLOBAL = X.VL_LIMITE_GLOBAL;

RAISE NOTICE 'TESTE 1 V_FINANCIAMENTO_GLOBAL:% | V_LIMITE_GLOBAL:% ',V_FINANCIAMENTO_GLOBAL,V_LIMITE_GLOBAL;

ELSE 

V_FINANCIAMENTO_GLOBAL = SOMA_SEMESTRE;
V_LIMITE_GLOBAL = V_FINANCIAMENTO_GLOBAL * 1.25;
RAISE NOTICE 'TESTE 2 V_FINANCIAMENTO_GLOBAL:% | V_LIMITE_GLOBAL:% ',V_FINANCIAMENTO_GLOBAL,V_LIMITE_GLOBAL;

END IF;


RAISE NOTICE 'V_FINANCIAMENTO_GLOBAL:% | V_LIMITE_GLOBAL:% ',V_FINANCIAMENTO_GLOBAL,V_LIMITE_GLOBAL;


  	INSERT INTO INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
	SELECT 
	NEXTVAL('INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITA_CO_CURSO_ASSOCIADO_ADITAMENTO_SEQ'), 
	NU_CPF, 
	CO_CURSO,
	CO_TURNO,
	CO_MANTENEDORA,
	CO_IES,
	CO_CAMPUS,
	SG_UF,
	CO_MUNICIPIO,
	NOW(), CO_USUARIO_INSCRICAO,
	QT_SEMESTRE_FINANCIAMENTO_DESTINO,
	NULL, NEXTVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ')
	FROM INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
	WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

	INSERT INTO INSCRICAO.TB_FIES_ADITAMENTO
	SELECT CURRVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ'), -- CO_ADITAMENTO
		CO_INSCRICAO, 
	       (SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO
		WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE), -- CO_SEMESTRE_ADITAMENTO 
	       33, -- CO_SITUACAO_ADITAMENTO 
	       CO_FINALIDADE_ADITAMENTO, 
	       'N', -- TP_ADITAMENTO
	       DT_LIMITE_CPSA, 
	       INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10), -- DT_LIMITE_COMPARECIMENTO_BANCO
	       INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15), -- DT_LIMITE_RETORNO_AGENTE_FINANC
	       NOW, -- DT_VALIDACAO_CPSA
	       NU_CPF, ST_BOLSISTA_PROUNI, 
	       NU_PERCENTUAL_PROUNI, NU_RG, DS_ORGAO_EMISSOR, DT_EMISSAO, CO_OCUPACAO, 
	       CO_ESTADO_CIVIL, NU_CPF_CONJUGE, NO_CONJUGE, VL_RENDA_FAMILIAR_BRUTA_MENSAL, 
	       VL_RENDA_PESSOAL_BRUTA_MENSAL, CO_CIDADE, CO_UF, DS_LOGRADOURO, 
	       DS_LOGRADOURO_COMP, DS_BAIRRO, DS_NUMERO, NU_CEP, NU_DDD_TELEFONE_RESIDENCIAL, 
	       NU_TELEFONE_RESIDENCIAL, NU_DDD_TELEFONE_CELULAR, NU_TELEFONE_CELULAR, 
	       SG_RACA_COR, ST_DEFICIENCIA, CO_TIPO_DEFICIENCIA, 
	       V_SEMESTRE, -- NU_SEMESTRE_REFERENCIA
	       CURRVAL('INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITA_CO_CURSO_ASSOCIADO_ADITAMENTO_SEQ'),      -- CO_CURSO_ASSOCIADO_ADITAMENTO 
	       VL_TAXA_JUROS_ANUAL, NU_MATRICULA, 
	       V_SEMESTRE_SEM_DESCONTO, -- VL_SEMESTRE_SEM_DESCONTO
	       V_SEMESTRE_COM_DESCONTO, -- VL_SEMESTRE_COM_DESCONTO
	       QT_SEMESTRE_CONCLUIDO+1, 
	       VL_RENDA_PER_CAPITA, NU_PERCENTUAL_COMPROMETIMENTO, QT_MESES_FINANC_SEMESTRE_ATUAL, 
	       NU_PERCENT_SOLICITADO_FINANC, ST_FINANCIAR_INTEGRALIDADE_SEMESTRE, 
	       CO_TIPO_PERIODICIDADE, QT_PERIODICIDADE, 
	       V_FINANCIAMENTO_EXERCICIO, -- VL_FINANCIAMENTO_EXERCICIO
	       V_FINANCIAMENTO_GLOBAL, -- VL_FINANCIAMENTO_GLOBAL 
	       NOW, -- DT_INCLUSAO
	       CO_MANTENEDORA, 
	       V_FINANCIADO_SEMESTRE, -- VL_FINANCIADO_SEMESTRE
	       V_SEMESTRE_ATUAL, -- VL_SEMESTRE_ATUAL
	       VL_SALDO_AUMENTO_SEMESTRALIDADE, VL_LIMITE_GLOBAL, 
	       DT_COMPARECIMENTO_BANCO, 
	       DT_RETORNO_BANCO, 
	       CO_MOTIVO_REJEICAO, 
	       DS_JUSTIFICATIVA_VALIDACAO, CO_USUARIO_INSCRICAO, 
	       ST_APROVEITAMENTO_ACADEMICO, 
	       NU_RIC, QT_SEMESTRE_FINANCIAMENTO, 
	       DT_CONCLUSAO_ADITAMENTO, ST_PASSO_ADITAMENTO, 
	       TP_ORIGEM_FINANCIAMENTO_GLOBAL, VL_GLOBAL_FGEDUC, DT_INICIO_COMPARECIMENTO_BANCO, 
	       CO_ORIGEM_DS_BAIRRO, 
	       'P', -- ST_APROVACAO_ALUNO
	        NOW, 
	       CO_CURSO_ASSOCIADO_ADITAMENTO_ORIGEM, TP_TRANSFERENCIA, DT_VALIDACAO_CPSA_DESTINO, 
	       DT_LIMITE_CPSA_DESTINO, DT_DESLIGAMENTO, QT_SEMESTRES_CURSO_DESTINO, 
	       QT_SEMESTRES_CURSO_ORIGEM, NU_PERCENT_SOLICITADO_FINANC_ORIGINAL, 
	       ST_TRANSFERENCIA_MANTENCA, NU_CONSULTAS_RECEITA, DT_ULTIMA_CONSULTA_RECEITA, 
	       CO_USUARIO_SSD, ST_MIGRADO, ST_TROCA_FIANCA, CO_TIPO_FIANCA, 
	       ST_ALTERACAO_BOLSA_PROUNI, ST_ELEVACAO_PERC_PROUNI, ST_DIREITO_TROCA_FIANCA, 
	       ST_DADOS_ATUALIZADOS, ST_ADITAMENTO_PRELIMINAR, VL_ULTRAPASSADO_MARGEM_PRELIMINAR, 
	       VL_AUTORIZADO_AJUSTE, VL_FINANCIADO_PRELIMINAR, DT_VALIDACAO_PRELIMINAR, 
	       CO_TIPO_PRELIMINAR, NU_SEMESTRE_A_CURSAR+1, VL_SEMESTRALIDADE_PARA_FIES, 
	       CO_ORGAO_EXPEDIDOR, SG_UF_EXPEDIDOR, ST_ENVIA_AF
	FROM INSCRICAO.TB_FIES_ADITAMENTO 
	WHERE CO_ADITAMENTO = X.CO_ADITAMENTO AND NU_CPF = V_CPF;


	INSERT INTO INSCRICAO.TB_FIES_ADITAMENTO_MOTIVO_VARIACAO_REAJUSTE 
	(
		CO_ADITAMENTO, CO_MOTIVO_VARIACAO, 
		DT_INCLUSAO, DS_JUSTIFICATIVA
	)
	VALUES 
	(
		CURRVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ'),
		2, NOW, 'SOLICITAÇAO DO FNDE POR MEIO DE DEMANDA JUDICIAL'
	);


	UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO 
	    SET VL_SEMESTRE_SEM_DESCONTO = V_SEMESTRE_SEM_DESCONTO,
		VL_SEMESTRE_COM_DESCONTO = V_SEMESTRE_COM_DESCONTO,
		VL_SEMESTRE_ATUAL = V_SEMESTRE_ATUAL,
		VL_SEMESTRALIDADE_PARA_FIES = V_SEMESTRALIDADE_PARA_FIES,
		VL_FINANCIAMENTO_EXERCICIO = V_FINANCIAMENTO_EXERCICIO,
		VL_FINANCIAMENTO_GLOBAL = V_FINANCIAMENTO_GLOBAL, 
		VL_FINANCIADO_SEMESTRE =V_FINANCIADO_SEMESTRE, 
		VL_LIMITE_GLOBAL = V_LIMITE_GLOBAL,
		QT_SEMESTRE_CONCLUIDO = X.QT_SEMESTRE_CONCLUIDO+1
	WHERE  CO_INSCRICAO = X.CO_INSCRICAO;

	IF (X.CO_TIPO_FIANCA = 1) THEN 
			
		INSERT INTO INSCRICAO.TB_FIES_FIADOR_ADITAMENTO
		SELECT 
			CO_FIADOR, CURRVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ'), NU_CPF, NO_FIADOR, 
			VL_RENDA_INFORMADA, VL_RENDA_COMPROMETIDA, 
			CO_ESTADO_CIVIL, NU_CPF_CONJUGE, NO_CONJUGE,
			DT_INCLUSAO, SG_PAIS, NU_RG, DS_ORGAO_EMISSOR
		FROM INSCRICAO.TB_FIES_FIADOR_ADITAMENTO
		WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

		
	END IF;

END IF;
	
END LOOP;

END;


COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;

