/*FNDE - Inclusão da bolsa Prouni - FIES - Sisfies Aluno
Ordem de trabalho # WO1339727*/

BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

DECLARE

	X RECORD;

	V_CPF VARCHAR := '39161856835';
	V_ADITAMENTO INT := 19462278;
	V_CO_SITUACAO_ADITAMENTO INT := 33;
	V_SEMESTRE_SEM_DESCONTO VARCHAR = '11130.00';
	V_SEMESTRE_COM_DESCONTO VARCHAR = '11130.00';
	V_SEMESTRE_ATUAL VARCHAR = '11130.00';
	V_SEMESTRALIDADE_PARA_FIES VARCHAR = '11130.00';
	V_NU_PERCENTUAL_PROUNI NUMERIC = '50.00'; -- PARA CASOS DE VALORES DE PROUNI A SEREM INSERIDOS
	V_NU_PERCENT_SOLICITADO_FINANC NUMERIC = '0.00'; --SE FOR MANTER O VALOR DA TABELA  0.00
	V_FINANCIADO_SEMESTRE VARCHAR;
	V_FINANCIAMENTO_GLOBAL VARCHAR;
	V_FINANCIAMENTO_EXERCICIO VARCHAR;
	SOMA_SEMESTRE VARCHAR;
	V_LIMITE_GLOBAL VARCHAR;
	V_SEMESTRE_COM_DESCONTO_CONTRATO VARCHAR;
	V_TP_ADITAMENTO VARCHAR;
	V_NO_USUARIO VARCHAR;
	V_CO_BANCO VARCHAR;
	V_ST_PROUNI CHAR;

BEGIN

	SELECT SUM(VL_FINANCIADO_SEMESTRE) INTO SOMA_SEMESTRE  FROM INSCRICAO.TB_FIES_ADITAMENTO WHERE NU_CPF = V_CPF AND CO_SITUACAO_ADITAMENTO = 49 AND CO_FINALIDADE_ADITAMENTO IN (1,2);
	SELECT NO_USUARIO INTO V_NO_USUARIO FROM INSCRICAO.TB_FIES_USUARIO_INSCRICAO WHERE NU_CPF = V_CPF;
	SELECT  
	CASE WHEN CO_BANCO = '001' THEN 'BB'::VARCHAR 
	WHEN CO_BANCO = '104' THEN 'CEF'::VARCHAR 
	ELSE 'NULL'::VARCHAR END 
	INTO V_CO_BANCO
	FROM INSCRICAO.TB_FIES_INSCRICAO  WHERE NU_CPF = V_CPF;

	FOR X IN
		SELECT * FROM  INSCRICAO.TB_FIES_ADITAMENTO WHERE CO_ADITAMENTO = V_ADITAMENTO

	LOOP
		RAISE NOTICE 'NOME:% CPF:%',V_NO_USUARIO,X.NU_CPF;
		RAISE NOTICE 'BANCO:%',V_CO_BANCO;
		RAISE NOTICE 'ADITAMENTO:% SEMESTRE:%',X.CO_ADITAMENTO,X.NU_SEMESTRE_REFERENCIA;
		V_TP_ADITAMENTO = X.TP_ADITAMENTO;

		IF (V_NU_PERCENT_SOLICITADO_FINANC = '0.00') THEN 
		V_NU_PERCENT_SOLICITADO_FINANC = X.NU_PERCENT_SOLICITADO_FINANC;
		END IF;	
			
		IF (V_NU_PERCENTUAL_PROUNI <> '0.00') THEN
			V_FINANCIADO_SEMESTRE = ROUND(V_SEMESTRE_ATUAL * (V_NU_PERCENTUAL_PROUNI/100),2);
			V_FINANCIADO_SEMESTRE = ROUND(V_FINANCIADO_SEMESTRE * (V_NU_PERCENT_SOLICITADO_FINANC/100),2);
			SOMA_SEMESTRE = SOMA_SEMESTRE + V_FINANCIADO_SEMESTRE;
			V_FINANCIAMENTO_EXERCICIO = V_SEMESTRE_COM_DESCONTO * (V_NU_PERCENT_SOLICITADO_FINANC /100);
			V_FINANCIAMENTO_GLOBAL = ROUND(X.QT_SEMESTRE_FINANCIAMENTO * V_FINANCIADO_SEMESTRE,2);
			V_LIMITE_GLOBAL = ROUND(V_FINANCIAMENTO_GLOBAL * 1.25,2);
			V_ST_PROUNI = 'S';
			
			RAISE NOTICE 'O ESTUDANTE POSSUI PROUNI:% ',V_NU_PERCENTUAL_PROUNI;
			RAISE NOTICE 'VALOR FINANCIADO SEMESTRE AJUSTADO:%',ROUND(V_FINANCIADO_SEMESTRE,2);
		END IF;

		IF (V_NU_PERCENTUAL_PROUNI = '0.00') THEN

			V_FINANCIADO_SEMESTRE = V_SEMESTRE_ATUAL * (V_NU_PERCENT_SOLICITADO_FINANC/100);
			SOMA_SEMESTRE = SOMA_SEMESTRE + V_FINANCIADO_SEMESTRE;
			V_FINANCIAMENTO_EXERCICIO = V_SEMESTRE_COM_DESCONTO * (V_NU_PERCENT_SOLICITADO_FINANC /100);
			V_FINANCIAMENTO_GLOBAL = ROUND(X.QT_SEMESTRE_FINANCIAMENTO * V_FINANCIADO_SEMESTRE,2);
			V_LIMITE_GLOBAL = ROUND(V_FINANCIAMENTO_GLOBAL * 1.25,2);
			V_ST_PROUNI = 'N';
			
			RAISE NOTICE 'O ESTUDANTE NÃO POSSUI PROUNI:% ',V_NU_PERCENTUAL_PROUNI;
			RAISE NOTICE 'VALOR FINANCIADO SEMESTRE AJUSTADO:%',ROUND(V_FINANCIADO_SEMESTRE,2);
		END IF;

		IF(SOMA_SEMESTRE <= X.VL_LIMITE_GLOBAL) THEN
			V_FINANCIAMENTO_GLOBAL = X.VL_FINANCIAMENTO_GLOBAL;
			V_LIMITE_GLOBAL = X.VL_LIMITE_GLOBAL;
			RAISE NOTICE 'MANTEVE OS VALORES DO FINANCIAMENTO GLOBAL:% | LIMITE GLOBAL:% ',V_FINANCIAMENTO_GLOBAL,V_LIMITE_GLOBAL;
			ELSE
			V_FINANCIAMENTO_GLOBAL = ROUND(SOMA_SEMESTRE,2);
			V_LIMITE_GLOBAL = ROUND(V_FINANCIAMENTO_GLOBAL * 1.25,2);
			V_TP_ADITAMENTO  = 'N';
			RAISE NOTICE 'FOI AJUSTADO OS VALORES DO FINANCIAMENTO GLOBAL:% | LIMITE_GLOBAL:% ',V_FINANCIAMENTO_GLOBAL,V_LIMITE_GLOBAL;
			RAISE NOTICE 'ADITAMENTO NãO SIMPLIFICADO:% ',V_TP_ADITAMENTO;
		END IF;


			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO  = V_ADITAMENTO;
			
			UPDATE INSCRICAO.TB_FIES_ADITAMENTO
					SET VL_SEMESTRE_SEM_DESCONTO = V_SEMESTRE_SEM_DESCONTO,
					VL_SEMESTRE_COM_DESCONTO= V_SEMESTRE_COM_DESCONTO,
					VL_SEMESTRE_ATUAL=V_SEMESTRE_ATUAL,
					VL_SEMESTRALIDADE_PARA_FIES=V_SEMESTRALIDADE_PARA_FIES,
					VL_FINANCIAMENTO_EXERCICIO= V_FINANCIAMENTO_EXERCICIO,
					VL_FINANCIAMENTO_GLOBAL= V_FINANCIAMENTO_GLOBAL,
					VL_FINANCIADO_SEMESTRE=V_FINANCIADO_SEMESTRE,
					VL_LIMITE_GLOBAL = V_LIMITE_GLOBAL,
					NU_PERCENT_SOLICITADO_FINANC = V_NU_PERCENT_SOLICITADO_FINANC, 
					NU_PERCENTUAL_PROUNI = V_NU_PERCENTUAL_PROUNI,
					ST_BOLSISTA_PROUNI = V_ST_PROUNI
			WHERE  CO_ADITAMENTO = V_ADITAMENTO;


		IF (V_CO_SITUACAO_ADITAMENTO = 34) THEN

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO
					SET 
					DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
					DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
					ST_APROVACAO_ALUNO = 'S',
					TP_ADITAMENTO = 'N',
					CO_SITUACAO_ADITAMENTO = V_CO_SITUACAO_ADITAMENTO
			WHERE  CO_ADITAMENTO = V_ADITAMENTO;


		ELSE 
			UPDATE INSCRICAO.TB_FIES_ADITAMENTO
					SET 
					DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
					DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
					CO_SITUACAO_ADITAMENTO = V_CO_SITUACAO_ADITAMENTO
			WHERE  CO_ADITAMENTO = V_ADITAMENTO;
		END IF;

		UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO
				SET VL_SEMESTRE_SEM_DESCONTO = V_SEMESTRE_SEM_DESCONTO,
				VL_SEMESTRE_COM_DESCONTO = V_SEMESTRE_COM_DESCONTO,
				VL_SEMESTRE_ATUAL = V_SEMESTRE_ATUAL,
				VL_SEMESTRALIDADE_PARA_FIES = V_SEMESTRALIDADE_PARA_FIES,
				VL_FINANCIAMENTO_EXERCICIO = V_FINANCIAMENTO_EXERCICIO,
				VL_FINANCIAMENTO_GLOBAL = V_FINANCIAMENTO_GLOBAL,
				VL_FINANCIADO_SEMESTRE = V_FINANCIADO_SEMESTRE,
				NU_PERCENT_SOLICITADO_FINANC = V_NU_PERCENT_SOLICITADO_FINANC, 
				VL_LIMITE_GLOBAL = V_LIMITE_GLOBAL
		WHERE  CO_INSCRICAO = X.CO_INSCRICAO;

	END LOOP;
END;
COMMIT;

ROLLBACK;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;