
BEGIN
	RAISE NOTICE 'INICIO DA TRANSACAO.';
	DECLARE 
		REC RECORD;
		QT_INSCRICAO INT := 0;
		EXIST_INSC BIGINT; 

	BEGIN 

		SELECT COUNT(*) INTO EXIST_INSC From 
		(SELECT DISTINCT I.NU_CPF, CO_SITUACAO_INSCRICAO, 
		NU_SEMESTRE_REFERENCIA FROM INSCRICAO.TB_FIES_INSCRICAO I,
		INSCRICAO.TB_FIES_CURSO_ASSOCIADO CA
		WHERE CA.NU_CPF = I.NU_CPF AND
		CO_SITUACAO_INSCRICAO = 3 AND 
		CA.CO_IES = 19049 AND
		CA.CO_CAMPUS = 1108104);

	
		FOR REC IN

			SELECT DISTINCT I.NU_CPF, I.CO_INSCRICAO,
			 CO_SITUACAO_INSCRICAO, NU_SEMESTRE_REFERENCIA 
			 FROM INSCRICAO.TB_FIES_INSCRICAO I,
			INSCRICAO.TB_FIES_CURSO_ASSOCIADO CA
			WHERE CA.NU_CPF = I.NU_CPF AND
			CO_SITUACAO_INSCRICAO = 3 AND 
			CA.CO_IES = 19049 AND
			CA.CO_CAMPUS = 1108104

		LOOP 

			IF (EXIST_INSC > 0) THEN 

				-- EXCLUIR COMPROVANTES
				DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_INSCRICAO = REC.CO_INSCRICAO; 

				UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
					CO_SITUACAO_INSCRICAO = 3
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;
				
				UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET
					DT_LIMITE_CONTRATACAO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
					DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
					DT_CONFIRMACAO_INSCRICAO = NOW,
					DT_VALIDACAO_CPSA = NOW,
					DT_CONCLUSAO_INSCRICAO = NOW
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				UPDATE INSCRICAO.TB_FIES_CURSO_ASSOCIADO SET 
					CO_IES = 18979,
					CO_CAMPUS = 1108103 
				WHERE NU_CPF = REC.NU_CPF;

			ELSE 
				RAISE NOTICE 'AJUSTE NÃO REALIZADO!!! FOI RETORNADO [%] INSCRIÇÕES TRAVADAS', EXIST_INSC;
			END IF;

			QT_INSCRICAO = QT_INSCRICAO +1;
			
		END LOOP;

		RAISE NOTICE 'NÚMERO DE INSCRIÇÕES AJUSTADAS: [%]', QT_INSCRICAO;

	END;

	COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
    RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;




