
BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

DECLARE 

P_CPF VARCHAR(11):= '07072982531';
P_SEMESTRE NUMERIC(5):= 22020;
P_ST_INSCRICAO INT:= 5;
EXIST_INSC BIGINT;
V_CRL_VAGA BIGINT;
VALIDA_PRE BIGINT;
STATUS_CONTRATADO BIGINT;
V_CO_BANCO CHARACTER(3);
LIMINAR BIGINT;
ANO VARCHAR:= (SUBSTRING (P_SEMESTRE, 2,5));


BEGIN 

	SELECT COUNT(*) 
	INTO EXIST_INSC 
	FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF;

	SELECT CO_BANCO 
	INTO V_CO_BANCO 
	FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF;	

	sELECT COUNT(*) 
	into LIMINAR 
	FROM INSCRICAO.TB_FIES_ABRANGENCIA_LIMINAR 
	WHERE NU_CPF = P_CPF;	
	
	IF (P_SEMESTRE::INT IN (22015,12016,22016,12017,22017)) THEN

		SELECT COUNT(*) INTO V_CRL_VAGA FROM INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
		WHERE CO_INSCRICAO = (
			SELECT CO_INSCRICAO FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF
		);
		
		SELECT COUNT(*) INTO VALIDA_PRE FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
		WHERE CO_INSCRICAO = (
			SELECT CO_INSCRICAO FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF
		) AND 
		ST_ATIVO = TRUE AND CO_PRE_INSCRICAO 
		IS NOT NULL GROUP BY DT_LOG_ALTERACAO LIMIT 1;
	END IF;

		
	if (V_CO_BANCO = '104') then

		select count(*) INTO STATUS_CONTRATADO from integracao.tb_fies_importa_contrato_fies imp, 
		inscricao.tb_fies_inscricao i
		where imp.co_cpf = i.nu_cpf and
		imp.st_contratacao = 'C' and
		imp.co_cpf = P_CPF
		;

	ELSE 
		select count (*) INTO STATUS_CONTRATADO 
		from integracao.tb_fies_importa_contrato_fies_bb
		where 	nu_cpf = P_CPF and
		co_motivo_situacao = '0000'
		and ds_motivo_situacao is null;
	END IF;

	
FOR REC IN

	SELECT CO_INSCRICAO, CO_SEMESTRE_INSCRICAO, V_CO_SEMESTRE_INSCRICAO, NU_SEMESTRE_REFERENCIA, 
	(ANO||'-'||MES||'-'||DIA) AS V_CONCLUSAO_INSC, PRORROGADO, LG_VALIDACAO  
	FROM (
	
		SELECT
		 NU_SEMESTRE_REFERENCIA, 
		(
		   SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
		   WHERE NU_SEMESTRE_REFERENCIA = I.NU_SEMESTRE_REFERENCIA )CO_SEMESTRE_INSCRICAO,

		 (
		   SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
		   WHERE NU_SEMESTRE_REFERENCIA = P_SEMESTRE)V_CO_SEMESTRE_INSCRICAO,
		 TF.CO_INSCRICAO, DS_SITUACAO_INSCRICAO, 
		 I.NU_CPF, NO_USUARIO, DT_LIMITE_CPSA, DT_LIMITE_CONTRATACAO, 
		 DT_LIMITE_RETORNO_AGENTE_FINANC,DT_CONFIRMACAO_INSCRICAO, 
		(
		   SELECT DT_LOG_ALTERACAO FROM AUDITORIA.VW_LG_FIES_INSCRICAO
		   WHERE CO_INSCRICAO = I.CO_INSCRICAO AND 
		   CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO 
		   ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
		) LG_VALIDACAO, 

		CASE 
			WHEN P.CO_SEMESTRE_ADITAMENTO IS NOT NULL AND 
			P.NU_SEMESTRE_PRORROGADO IS NOT NULL AND
			P.CO_INSCRICAO IS NOT NULL
			THEN 'S' 
			ELSE 
			'N'
		END PRORROGADO,
		DT_CONCLUSAO_INSCRICAO, 
		(SUBSTRING (NU_SEMESTRE_REFERENCIA::VARCHAR, 1, 1)) SEMEST,
		(30::VARCHAR) DIA,
		CASE 
		WHEN SUBSTRING(NU_SEMESTRE_REFERENCIA, 1,1) = '1' THEN '06'
		ELSE 
		'12'
		END MES
			
		FROM  INSCRICAO.TB_FIES_INSCRICAO I
		INNER JOIN INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO TF ON I.CO_INSCRICAO = TF.CO_INSCRICAO
		INNER JOIN INSCRICAO.TB_FIES_USUARIO_INSCRICAO UI ON UI.NU_CPF = I.NU_CPF
		INNER JOIN INSCRICAO.TB_FIES_SITUACAO_INSCRICAO ST USING (CO_SITUACAO_INSCRICAO)
		LEFT JOIN INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA P ON P.CO_INSCRICAO = I.CO_INSCRICAO
		WHERE I.NU_CPF = P_CPF
	)


LOOP 

	IF (EXIST_INSC > 0) THEN 

		IF (REC.V_CO_SEMESTRE_INSCRICAO > REC.CO_SEMESTRE_INSCRICAO) THEN
			RAISE NOTICE 'A INSCRICAO ESTA SENDO POSTERGADA PARA %', P_SEMESTRE;
			
			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
			NU_SEMESTRE_REFERENCIA = P_SEMESTRE
			WHERE NU_CPF = P_CPF;
					
			IF (REC.PRORROGADO =  'S') THEN
				UPDATE INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA SET
				CO_SEMESTRE_ADITAMENTO = REC.CO_SEMESTRE_INSCRICAO,
				DT_PERGUNTA_INSCRICAO_PRORROGAD = NOW,
				NU_SEMESTRE_PRORROGADO = P_SEMESTRE
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO; 

			ELSE
				INSERT INTO  INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA
				(CO_SEMESTRE_ADITAMENTO, CO_INSCRICAO, CO_PERGUNTA_OPCAO, 
				 CO_USUARIO_SSD, DT_PERGUNTA_INSCRICAO_PRORROGAD,
				 NU_SEMESTRE_PRORROGADO, CO_PRE_INSCRICAO)
				VALUES 
				(REC.CO_SEMESTRE_INSCRICAO, REC.CO_INSCRICAO,
				 25, 2574677, NOW, P_SEMESTRE::NUMERIC, NULL);	
			 END IF;
		END IF;
	

		IF (P_SEMESTRE IN ('22015','12016', '22016', '12017', '22017')) THEN

			IF (V_CRL_VAGA > 0) THEN 

				UPDATE INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO SET
				DT_PRAZO_CONCLUSAO_INSCRICAO = NOW+90
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;
			ELSE 
				INSERT INTO INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO
				SELECT
					    NEXTVAL('INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INS_CO_CONTROLE_VAGA_PRE_INSCRICA_SEQ'), 
					    CO_SEMESTRE, CO_MANTENEDORA, 
					    CO_IES, CO_CAMPUS, CO_CURSO, CO_TURNO, upper('L')||lower('IMINAR'), CO_PRE_INSCRICAO, 
					    NOW(), NOW()+90, CO_INSCRICAO, 
					    TRUE, CO_REM_INSCRICAO, NULL
				 FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
				ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1;
			END IF;

			IF (VALIDA_PRE > 0) THEN 
				RAISE NOTICE 'VAGA DA PRE-INSCRICAO PROCESSO REGULAR';
				
				UPDATE FIES_PREINSCRICAO.TB_PRE_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = 3, 
				CO_TIPO_VENCIMENTO = NULL 
				WHERE CO_INSCRICAO::INT = (					
					SELECT CO_PRE_INSCRICAO::INT FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
					WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
					ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
				);
			ELSE
				RAISE NOTICE 'VAGA DA PRE-INSCRICAO PROCESSO REMANSCENTE';
				UPDATE FIES_REMANESCENTE.TB_REM_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = 3, 
				CO_TIPO_VENCIMENTO = NULL 
				WHERE CO_INSCRICAO::INT = (					
					SELECT CO_REM_INSCRICAO::INT FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
					WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
					ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
				);

				INSERT INTO  INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA
				(CO_SEMESTRE_ADITAMENTO, CO_INSCRICAO, CO_PERGUNTA_OPCAO, 
				CO_USUARIO_SSD, DT_PERGUNTA_INSCRICAO_PRORROGAD,
				NU_SEMESTRE_PRORROGADO, CO_PRE_INSCRICAO)
				VALUES 
				(REC.CO_SEMESTRE_INSCRICAO, REC.CO_INSCRICAO, 25, 2574677, NOW, P_SEMESTRE::NUMERIC, NULL);
								
			END IF;
		END IF;

		CASE 
			WHEN (P_ST_INSCRICAO  IN (1,2,7) ) THEN
			
				IF (P_ST_INSCRICAO = 1) THEN
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "EM PREENCIMENTO (%)"', P_ST_INSCRICAO;
				END IF;
				
				IF (P_ST_INSCRICAO = 2) THEN 
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "PENDENTE DE VALIDAÇAO PELA CPSA (%)"', P_ST_INSCRICAO;
				END IF;
				
				IF (P_ST_INSCRICAO = 7) THEN 
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "REABERTO PARA CORREÇAO (%)"', P_ST_INSCRICAO;

				END IF;

				UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET
				DT_LIMITE_CPSA = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				DT_CONFIRMACAO_INSCRICAO = NOW
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				if (LIMINAR > 0)  THEN

					RAISE NOTICE 'PRORROGANDO OS PRAZOS DA LIMINAR (%)', LIMINAR;
					
					UPDATE INSCRICAO.TB_FIES_LIMINAR SET 
					DT_FIM_VALIDADE = NOW+60
					WHERE CO_LIMINAR IN (
						SELECT CO_LIMINAR FROM INSCRICAO.TB_FIES_ABRANGENCIA_LIMINAR
						WHERE NU_CPF = P_CPF
					);

				else 
					raise NOTICE 'SEM LIMINAR NA INSCRIÇAO (SISFIES)';
					

				END IF;
				
			WHEN (P_ST_INSCRICAO = 3) THEN
				RAISE NOTICE 'SITUACAO VALIDADO PELA CPSA';

				-- EXCLUIR COMPROVANTES
				DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_INSCRICAO = REC.CO_INSCRICAO; 


				UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;
				
				UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET
				DT_LIMITE_CONTRATACAO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
				DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				DT_CONFIRMACAO_INSCRICAO = NOW,
				DT_VALIDACAO_CPSA = NOW,
				DT_CONCLUSAO_INSCRICAO = REC.V_CONCLUSAO_INSC::DATE
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				IF (REC.V_CO_SEMESTRE_INSCRICAO < REC.CO_SEMESTRE_INSCRICAO) THEN
					RAISE NOTICE 'O SEMESTRE DA INSCRIÇAO SERA RETROAGIDO DE % PARA % (GAMBIARRA ALTORIZADA PELO FNDE) ...', REC.NU_SEMESTRE_REFERENCIA, P_SEMESTRE;
					UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
						NU_SEMESTRE_REFERENCIA = P_SEMESTRE
					WHERE NU_CPF = P_CPF;		
				END IF;
				
			WHEN (P_ST_INSCRICAO = 5) THEN

				IF (STATUS_CONTRATADO > 0) THEN

				
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "CONTRATADO (%)"', P_ST_INSCRICAO;    
					  
					UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
					CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO  
					WHERE NU_CPF = P_CPF;   

					PERFORM CONSULTA.FN_FIES_PROCESSAMENTO_VALA(
					    REC.CO_INSCRICAO,'N', NULL);
				ELSE 


					RAISE NOTICE 'NÃO FOI LOCALIZADO O ARQUIVO DA CONTRATAÇÃO DA INSCRIÇÃO DO AGENTE FINANCEIRO (%)', V_CO_BANCO;
				END IF;
				
			ELSE 

				RAISE NOTICE '(ERRO) ALTERAÇOES NAO REALIZADAS PARA ESTE TIPO DE SITUAÇAO DA INSCRIÇAO (%)', P_ST_INSCRICAO;   
			
		END CASE;
	ELSE 
		RAISE NOTICE 'NAO EXISTE INSCRIÇAO NA BASE DE DADOS DO SISFIES';
	END IF;

END LOOP;

END;

COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;



/*



-- verificar se o banco(BB) nos enviou contratação ou derrubada de inscricao
select *
from 	integracao.tb_fies_importa_contrato_fies_bb
where 	nu_cpf in ('13590946792')
order 	by dt_inclusao_registro desc;

-- verifica se o banco(CAIXA) nos enviou contratação ou derrubada de aditamento de renovação
select co_cpf,
	ltrim(nu_sem_aditamento,0)|| '/' ||aa_aditamento semestre_ano,
	nu_aditamento_fies,
	st_aditamento||' - '||
	case
		when st_aditamento in ('C','S') then 'CONTRATADO'
		WHEN st_aditamento = 'N' then 'NÃO CONTRATADO'
		else 'SEM IDENTIFICAÇÃO'
	end st_aditamento,
	ds_motivo_situacao,
	dt_inclusao_registro,
	vr_aditamento,
	co_arquivo_recebido,*	 
from	integracao.tb_fies_importa_aditamento
where	co_cpf = '00400014076'
	--and trim(nu_aditamento_fies) in ('3626938','00003626938')
order by 
	aa_aditamento::numeric,
	nu_sem_aditamento::numeric, 
	dt_inclusao_registro desc;

-- verifica se o banco(bb) nos enviou contratação ou derrubada de aditamento de renovação
select ia.ds_tipo_liminar,ui.no_usuario, ia.*
  from integracao.tb_fies_importa_aditamento_bb ia,
       inscricao.tb_fies_usuario_inscricao ui 
 where ia.nu_cpf = ui.nu_cpf
   and ia.nu_cpf in ('05076525338')
   --and ia.co_aditamento = lpad(05076525338,11,0)
   --and ia.co_aditamento in ('00005264787','00005163418','00005258074')
   --and co_motivo_situacao = '0000'
order by ui.no_usuario

      
--verificar se o banco(CAIXA) nos enviou contratação ou derrubada de suspensão ou encerramento.
select * from integracao.tb_fies_importa_ocorrencia_contrato_cef where co_cpf in ('00400014076') order by dt_inclusao_registro;

--verificar se o banco(BB) nos enviou contratação ou derrubada de suspensão ou encerramento.
select ui.no_usuario, ioc_bb.co_cpf, ioc_bb.co_ocorrencia, ioc_bb.ic_situacao_ocorrencia, ioc_bb.co_motivo_situacao, 
	ioc_bb.nu_semestre_referencia || '/' || ioc_bb.nu_ano_referencia sem_ano_referencia, ioc_bb.dt_inclusao_registro, 
	ar.no_arquivo,
	ioc_bb.*
from 	integracao.tb_fies_importa_ocorrencia_contrato_bb ioc_bb,
	inscricao.tb_fies_usuario_inscricao ui,
	integracao.tb_fies_arquivo_recebido ar
where 	ioc_bb.co_cpf = ui.nu_cpf
	and ioc_bb.co_arquivo_recebido = ar.co_arquivo_recebido
	and ioc_bb.co_cpf in ('09709915410')
order	by ioc_bb.dt_inclusao_registro

--Criticas do A.F. para o sisFIES
select * from integracao.tb_fies_importa_critica_retorno where nu_cpf = to_char(lpad('00400014076',11,0)) order by dt_inclusao_registro desc;

--Criticas do SisFIES para o A.F.
select co_critica,ds_observacao,* from integracao.tb_fies_acompanha_arq_recebido where co_id_registro like '%06030470175%' order by dt_inclusao desc

*/