/*FNDE - #aditamento de renovação- liminar MT - FIES - Sisfies Aluno
Ordem de trabalho # WO1326189*/


DECLARE
V_CPF VARCHAR :=  '06082944119';
V_FIANCA  INT := 3;
X RECORD;	

BEGIN
	RAISE NOTICE 'INICIO DA TRANSACAO.';
	RAISE NOTICE '';

	FOR X IN 

		SELECT A.NU_SEMESTRE_REFERENCIA AS SEMESTRE_REFERENCIA,I.NU_CPF, 
		I.CO_INSCRICAO, A.CO_FINALIDADE_ADITAMENTO, 
		case 
		when I.CO_BANCO = '104' Then 'CEF'::varchar
		when I.CO_BANCO = '001' Then 'BB'::varchar
		end BANCO, I.CO_TIPO_FIANCA as FIANCA_INSCRICAO, 
		A.CO_TIPO_FIANCA AS FIANCA_ADITAMENTO, I.DT_ACEITE_FGEDUC_CONCOMITANTE, I.DT_ACEITE_FGEDUC, 
		I.DT_ACEITE_FIANCA_SOLIDARIA,(
			   SELECT DT_LOG_ALTERACAO FROM 
			   AUDITORIA.VW_LG_FIES_INSCRICAO 
			   WHERE NU_CPF = I.NU_CPF AND 
			   CO_SITUACAO_INSCRICAO = 5 
			   ORDER BY DT_LOG_ALTERACAO ASC LIMIT 1) DT_FIANCA, A.ST_TROCA_FIANCA, A.ST_DIREITO_TROCA_FIANCA, 
		A.CO_SITUACAO_ADITAMENTO,I.CO_BANCO, A.ST_APROVACAO_ALUNO, A.TP_ADITAMENTO,
		A.DT_LIMITE_COMPARECIMENTO_BANCO, A.DT_LIMITE_RETORNO_AGENTE_FINANC, 
		A.CO_SITUACAO_ADITAMENTO, FA.CO_FIADOR, 
		CASE 
		WHEN LIM21.NU_CPF ISNULL THEN 'LIMINAR 21 NAO ESTA PRESENTE NESTE FINANCIAMENTO'
		WHEN LIM21.NU_CPF IS NOT NULL THEN 'LIMINAR 21 ESTA PRESENTE NESTE FINANCIAMENTO' 
		ELSE 'RESULTADO NAO IDENTIFICADO' 
		END STATUS_LIM21, (
		SELECT CO_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO 
		WHERE NU_CPF = I.NU_CPF
		 AND CO_FINALIDADE_ADITAMENTO = 2 
		 ORDER  BY CO_SEMESTRE_ADITAMENTO DESC LIMIT 1
		 ) MAX_ADITAMENTO, A.CO_ADITAMENTO
		FROM INSCRICAO.TB_FIES_INSCRICAO I
		LEFT JOIN INSCRICAO.TB_FIES_ADITAMENTO A ON A.CO_INSCRICAO = I.CO_INSCRICAO
		LEFT JOIN INSCRICAO.TB_FIES_FIADOR_ADITAMENTO FA ON FA.CO_ADITAMENTO = A.CO_ADITAMENTO
		LEFT JOIN INSCRICAO.TB_FIES_FIADOR_INSCRICAO FI ON FI.CO_INSCRICAO = I.CO_INSCRICAO
		LEFT JOIN AUX.TB_FIES_AJUSTA_LIMINAR_21 LIM21 ON LIM21.NU_CPF = I.NU_CPF
		WHERE I.NU_CPF = V_CPF ORDER BY A.CO_SEMESTRE_ADITAMENTO DESC LIMIT 1
		
	LOOP
		
		RAISE NOTICE 'CPF: %, ADITAMENTO %, SEMESTRE: %',X.NU_CPF, X.CO_ADITAMENTO, X.SEMESTRE_REFERENCIA;
		RAISE NOTICE 'FIANCA ADITAMENTO: %',X.FIANCA_ADITAMENTO;
		
		if (X.BANCO = 'CEF') then
		RAISE NOTICE 'AGENTE FINANCEIRO CEF';
					
			update INSCRICAO.TB_FIES_ADITAMENTO SET 
			ST_TROCA_FIANCA = 'S',
			ST_DIREITO_TROCA_FIANCA = 'S'
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
		end if;	
		IF (X.BANCO  = 'BB') then
		raise notice 'AGENTE FINANCEIRO BB';
		
			update INSCRICAO.TB_FIES_ADITAMENTO SET 
			ST_TROCA_FIANCA = 'S'
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
		
			select COUNT(*) AS lim21 from 
			AUX.TB_FIES_AJUSTA_LIMINAR_21 
			WHERE NU_CPF = V_CPF;

			if (lim21 < 1) then
				INSERT INTO AUX.TB_FIES_AJUSTA_LIMINAR_21 (NU_CPF) VALUES (V_CPF);
			ELSE 
				RAISE NOTICE 'A LIMINAR 21 JA ESTA PRESENTE NA TABELA AUX';
			END IF;		
		
		END IF;

	case    
		WHEN (V_FIANCA = 1) THEN

			raise NOTICE 'A GARANTIA DE FIANÇA ESTA SENDO ALTERADA PARA CONVENCIONAL';
			
			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET
			CO_TIPO_FIANCA = V_FIANCA,
			DT_ACEITE_FGEDUC_CONCOMITANTE = NULL,
			DT_ACEITE_FGEDUC= null,
			DT_ACEITE_FIANCA_SOLIDARIA = NULL
			WHERE CO_INSCRICAO = X.CO_INSCRICAO AND NU_CPF = V_CPF;

			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET 
			CO_TIPO_FIANCA = V_FIANCA,
			TP_ADITAMENTO = 'N'
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
			
			if (select count(*) from inscricao.tb_fies_fiador_aditamento 
			where co_aditamento = X.CO_ADITAMENTO) > 0 then

				UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
				CO_SITUACAO_ADITAMENTO = 34, 				
				DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
				DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				ST_APROVACAO_ALUNO = 'S',
				CO_TIPO_FIANCA = V_FIANCA,
				DT_VALIDACAO_CPSA = NOW
				WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
			else 

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
			CO_SITUACAO_ADITAMENTO = 41,
			ST_APROVACAO_ALUNO = 'P'
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			raise NOTICE 'ADITAMENTO REABERTO PARA O (A) ESTUDANTE CADASTRAR O FIADOR';
			end if;
			
			Exit;			
		WHEN (V_FIANCA = 2) THEN 
			raise NOTICE 'A GARANTIA DE FIANÇA ESTA SENDO ALTERADA PARA SOLIDARIA';
			DELETE INSCRICAO.TB_FIES_FIADOR_ADITAMENTO WHERE CO_ADITAMENTO IN (
			SELECT CO_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO WHERE CO_INSCRICAO = X.CO_INSCRICAO
			);

			DELETE INSCRICAO.TB_FIES_FIADOR_INSCRICAO WHERE CO_INSCRICAO = X.CO_INSCRICAO;

			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET
			CO_TIPO_FIANCA = V_FIANCA,
			DT_ACEITE_FGEDUC_CONCOMITANTE = NULL,
			DT_ACEITE_FGEDUC= NULL,
			DT_ACEITE_FIANCA_SOLIDARIA = X.DT_FIANCA
			WHERE CO_INSCRICAO = X.CO_INSCRICAO AND NU_CPF = V_CPF;

			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
			CO_SITUACAO_ADITAMENTO = 34, 
			TP_ADITAMENTO = 'N',
			DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
			DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
			ST_APROVACAO_ALUNO = 'S',
			DT_VALIDACAO_CPSA = NOW,
			CO_TIPO_FIANCA = V_FIANCA
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
			
			Exit;
		WHEN (V_FIANCA = 3) THEN

			raise NOTICE 'A GARANTIA DE FIANÇA ESTA SENDO ALTERADA PARA FGEDUC';
			
			DELETE INSCRICAO.TB_FIES_FIADOR_ADITAMENTO WHERE CO_ADITAMENTO IN (
			SELECT CO_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO WHERE CO_INSCRICAO = X.CO_INSCRICAO
			);

			DELETE INSCRICAO.TB_FIES_FIADOR_INSCRICAO WHERE CO_INSCRICAO = X.CO_INSCRICAO;

			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET
			CO_TIPO_FIANCA = V_FIANCA,
			DT_ACEITE_FGEDUC_CONCOMITANTE = NULL,
			DT_ACEITE_FIANCA_SOLIDARIA = NULL,
			DT_ACEITE_FGEDUC = X.DT_FIANCA
			WHERE CO_INSCRICAO = X.CO_INSCRICAO AND NU_CPF = V_CPF;

			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
			CO_SITUACAO_ADITAMENTO = 34, 
			TP_ADITAMENTO = 'N',
			DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
			DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
			ST_APROVACAO_ALUNO = 'S',
			CO_TIPO_FIANCA = V_FIANCA,
			DT_VALIDACAO_CPSA = NOW
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
			
			Exit;
		WHEN (V_FIANCA = 4) THEN

			raise NOTICE 'A GARANTIA DE FIANÇA ESTA SENDO ALTERADA PARA CONVENCIONAL+FGEDUC';

			DELETE INSCRICAO.TB_FIES_FIADOR_INSCRICAO WHERE CO_INSCRICAO = X.CO_INSCRICAO;

			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET
			CO_TIPO_FIANCA = V_FIANCA,
			DT_ACEITE_FGEDUC_CONCOMITANTE = X.DT_FIANCA,
			DT_ACEITE_FIANCA_SOLIDARIA = NULL,
			DT_ACEITE_FGEDUC= null
			WHERE CO_INSCRICAO = X.CO_INSCRICAO AND NU_CPF = V_CPF;

			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			if (select count(*) from inscricao.tb_fies_fiador_aditamento where co_aditamento = X.CO_ADITAMENTO) > 0 then

				UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
				CO_SITUACAO_ADITAMENTO = 34, 
				TP_ADITAMENTO = 'N',
				DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
				DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				ST_APROVACAO_ALUNO = 'S',
				CO_TIPO_FIANCA = V_FIANCA,
				DT_VALIDACAO_CPSA = NOW
				WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
			
			else				
				UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
				CO_SITUACAO_ADITAMENTO = 41, 
				TP_ADITAMENTO = 'N',
				DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
				DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				ST_APROVACAO_ALUNO = 'P',
				DT_VALIDACAO_CPSA = NOW,
				CO_TIPO_FIANCA = V_FIANCA
				WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;
				
				raise NOTICE 'ADITAMENTO REABERTO PARA O (A) ESTUDANTE CADASTRAR O FIADOR';
			end if;
			
			Exit;
		WHEN (V_FIANCA = 5) THEN

			raise NOTICE 'A GARANTIA DE FIANÇA ESTA SENDO ALTERADA PARA FIANCA SOLIDARIA+FGEDUC';
			
			DELETE INSCRICAO.TB_FIES_FIADOR_ADITAMENTO WHERE CO_ADITAMENTO IN (
			SELECT CO_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO WHERE CO_INSCRICAO = X.CO_INSCRICAO
			);

			DELETE INSCRICAO.TB_FIES_FIADOR_INSCRICAO WHERE CO_INSCRICAO = X.CO_INSCRICAO;

			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET
			CO_TIPO_FIANCA = V_FIANCA,
			DT_ACEITE_FGEDUC_CONCOMITANTE = X.DT_FIANCA,
			DT_ACEITE_FIANCA_SOLIDARIA = NULL,
			DT_ACEITE_FGEDUC= null
			WHERE CO_INSCRICAO = X.CO_INSCRICAO AND NU_CPF = V_CPF;

			DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET
			CO_SITUACAO_ADITAMENTO = 34, 
			TP_ADITAMENTO = 'N',
			DT_LIMITE_COMPARECIMENTO_BANCO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
			DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
			ST_APROVACAO_ALUNO = 'S',
			DT_VALIDACAO_CPSA = NOW,
			CO_TIPO_FIANCA = V_FIANCA
			WHERE CO_ADITAMENTO = X.CO_ADITAMENTO;

			Exit;
			
	else 
		raise NOTICE 'GARANTIA INEXISTENTE  - ALTERAÇAO NAO REALIZADA';
	END case;
	
	END LOOP;

	COMMIT;
	RAISE NOTICE '';
	RAISE NOTICE 'TRANSAÇAO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION 
	WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE '% %', SQLERRM, SQLSTATE;
END;



	
	





	
	