/*FNDE - DEMANDA - PROCESSO SEI 23034.029352/2020-15 - COSAE - FIES - SISFIES ALUNO
ORDEM DE TRABALHO # WO1332420*/

BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

DECLARE 
	
	P_CO_IES_VIGENTE INT := 2132;
	P_CO_MANTENEDORA INT := 1404;
	P_CO_IES_EXTINTO INT;
	P_CO_CURSO INT;
	
	REC RECORD;
	
BEGIN

FOR REC IN

	SELECT DISTINCT NU_CPF, CA.CO_IES, CA.CO_CURSO  
	FROM INSCRICAO.TB_FIES_CURSO_ASSOCIADO CA, 
	VW_FIES_CURSO VW
	WHERE 
	VW.CO_CURSO = CA.CO_CURSO AND
	VW.CO_IES = CA.CO_IES AND
	VW.CO_MANTENEDORA = CA.CO_MANTENEDORA AND
	CA.CO_MANTENEDORA = P_CO_MANTENEDORA 
	AND CA.CO_IES IN (1226, 2146)
	AND ST_VINCULO_ATIVO_EMEC = 'N'
	AND DT_PERDA_VINCULO_EMEC IS NOT NULL


LOOP 

	P_CO_CURSO := REC.CO_CURSO;
	P_CO_IES_EXTINTO := REC.CO_IES;

	PERFORM AUX.FN_ATUALIZA_IES_EXTINTA_CURSO(
		P_CO_IES_EXTINTO,
		P_CO_IES_VIGENTE,
		P_CO_CURSO
	);

 

END LOOP;

END;

COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;