-- CONSULTAS - ORACLE

/* Consulta arquivo que foi enviado para análise bancária */
  /*
  TABELA FIES_FINANCIAMENTO.TB_FIN_ARQ_CANDIDATO_PRIV
  COLUNA TP_ARQ_CANDIDATO_PRIV

  1 - ENVIO PARA ANÁLISE
  2 - RETORNO DA ANÁLISE
  3 - ENVIO PARA A CONTRATAÇÃO
  4 - RETORNO DA CONTRATAÇÃO
  5 - RESPOSTA ENVIO CONTRATAÇÃO
  6 - RESPOSTA CANCELAMENTO DA CONTRATAÇÃO
---------------------------------------------------
  TABELA FIES_FINANCIAMENTO.TH_FIN_ARQ_CANDIDATO_PRIV  
  COLUNA TP_H_ARQ_CANDIDATO_PRIV

  1 - GERADO
  2 - BAIXADO
  3 - PROCESSADO
  4 - RECEBIDO
  */

 SELECT hacp.DT_H_ARQ_CANDIDATO_PRIV,  b.CO_BANCO,
  b.NO_BANCO, acp.*
FROM FIES_FINANCIAMENTO.TB_FIN_ARQ_CANDIDATO_PRIV acp
  join FIES_FINANCIAMENTO.TH_FIN_ARQ_CANDIDATO_PRIV hacp
  on hacp.CO_ARQ_CANDIDATO_PRIV = acp.CO_ARQ_CANDIDATO_PRIV
  JOIN FIES_GLOBAL.TB_GLB_BANCO b
    ON b.DS_TOKEN = acp.DS_TOKEN
WHERE
  TP_ARQ_CANDIDATO_PRIV = 3 AND
  TX_CONTEUDO_ARQ LIKE '%86311221578%'; 


  
  -- AUDITORIA DA INSCRIÇÃO
SELECT I.CO_INSCRICAO,I.CO_USUARIO, PF.NU_CPF, I.CO_SEMESTRE, 
I.CO_SITUACAO_INSCRICAO||'-'||DS_SITUACAO_INSCRICAO AS SITUACAO_INSCRICAO, 
CASE 
 WHEN I.TP_USUARIO = 2 THEN 'REMANESCENTE'
 ELSE 'REGULAR' END TIPO_USUARIO, 
 DT_OPERACAO_LOG, TP_OPERACAO_LOG, 
 NO_USUARIO_BANCO_LOG, NO_USUARIO_OS_LOG
 FROM FIES_PREINSCRICAO.TB_PRE_INSCRICAO I
 JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO U ON U.CO_USUARIO = I.CO_USUARIO
 JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA PF ON PF.CO_PESSOA = U.CO_PESSOA
 LEFT JOIN FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO C ON 
 C.CO_INSCRICAO = I.CO_INSCRICAO AND 
 C.TP_USUARIO = I.TP_USUARIO AND 
 I.CO_SEMESTRE = C.CO_SEMESTRE
JOIN FIES_AUDITORIA.LG_PRE_INSCRICAO T ON I.CO_INSCRICAO = T.CO_INSCRICAO
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_SITUACAO_INSCRICAO ST ON ST.CO_SITUACAO_INSCRICAO = I.CO_SITUACAO_INSCRICAO
WHERE 
PF.NU_CPF IN ('10061891908') AND C.CO_SEMESTRE = 20202 AND I.TP_USUARIO = 2
ORDER BY DT_OPERACAO_LOG;


select * from FIES_PREINSCRICAO.TB_PRE_RESTRICAO_ESTUDANTE where nu_cpf = '75098385253';

select i.co_inscricao, i.co_semestre, i.co_situacao_inscricao, 'Regular' as Tipo
 from FIES_PREINSCRICAO.TB_PRE_INSCRICAO i
 join FIES_PREINSCRICAO.TB_PRE_USUARIO u on u.CO_USUARIO = i.co_usuario
 join FIES_GLOBAL.TB_GLB_PESSOA_FISICA pf on pf.co_pessoa = u.co_pessoa
where pf.nu_cpf = '05949031571'

select * from FIES_FINanciamento.TB_FIN_CANDIDATO WHERE CO_USUARIO = 7742632;
SELECT * FROM FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PUBLICO WHERE CO_USUARIO = 7742632;
update FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PUBLICO set 
CO_USUARIO = 7742632;
SELECT * FROM FIES_FINANCIAMENTO.VW_H_FIN_CANDIDATO_PUBLICO WHERE CO_USUARIO = 7742632;
SELECT * FROM FIES_AUDITORIA.LG_FIN_CANDIDATO_PUBLICO WHERE CO_USUARIO = 7742632;


update FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PUBLICO set 
CO_AGENCIA = 30192,
TP_FIANCA = 2,
QT_SEMESTRE_CURSO = 12,
QT_SEMESTRE_CONCLUIDO = 0,
QT_SEMESTRE_FINANCIADO = 12,
PC_SOLICITADO = 48.98,
VL_SEMESTRE_FIES = 61243,
VL_ATUAL_COM_DESCONTO = 61243,
VL_FINANCIADO_SEMESTRE = 29996.82,
VL_FINANCIADO_GLOBAL = 312823.99,
VL_LIMITE_GLOBAL = 391029.98,
VL_TAXA_JUROS = 0,
NU_ABA = 4,
PC_FINANCIAMENTO_MAXIMO = 88.39
where CO_USUARIO = 7742632;

delete FIES_FINANCIAMENTO.TH_FIN_CANDIDATO_PUBLICO where CO_candidato_publico  = 7742632 and  co_h_candidato_publico in (1495657);
update FIES_FINANCIAMENTO.TH_FIN_CANDIDATO_PUBLICO set co_situacao_financiamento = 16 WHERE CO_candidato_publico  = 7742632;


SELECT * FROM FIES_FINANCIAMENTO.TH_FIN_CANDIDATO_PUBLICO where CO_candidato_publico  = 7742632

select TF.CO_CURSO, TF.CO_TURNO,PCO.*
from FIES_PREINSCRICAO.TB_PRE_INSCRICAO i
left join FIES_PREINSCRICAO.TB_PRE_USUARIO u on u.CO_USUARIO = i.co_usuario
left join FIES_GLOBAL.TB_GLB_PESSOA_FISICA pf on pf.co_pessoa = u.co_pessoa
left join FIES_PREINSCRICAO.TB_PRE_TERMO_FINANCIAMENTO TF ON TF.CO_INSCRICAO = i.CO_INSCRICAO
JOIN FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO PCO ON PCO.CO_INSCRICAO = i.CO_INSCRICAO
where pf.nu_cpf = '41715611837';


 
select * from fies_global.tb_glb_pessoa_fisica where nu_cpf = '41545102821' -- co_pessoa = 138138
select * from fies_preinscricao.tb_pre_usuario where co_pessoa = '138138'  -- co_usuario = 120376
select * from  FIES_GLOBAL.TB_GLB_COMPL_PESSOA_FISICA WHERE co_pessoa = 3284418 (verificar tipo de deficiencia)
select * from fies_preinscricao.tb_pre_inscricao where co_usuario = '120376' --co_inscricao = 531818
select * from fies_preinscricao.tb_pre_ranking_classificacao where co_inscricao in (988142 ,  118478)
select * from fies_preinscricao.tb_pre_ranking_classificacao where co_curso = '82227' and co_turno = '10070' and co_semestre = '20161' order by nu_media_enem desc  -- ranking da classificação


select * from FIES_FINanciamento.TB_FIN_CANDIDATO WHERE CO_USUARIO = 8592164;
SELECT * FROM FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PUBLICO WHERE CO_USUARIO = 7742632;
--  Regular:

 

--  Consulta rem-Inscrição
SELECT * 
FROM FIES_GLOBAL.TB_GLB_PESSOA_FISICA GPF
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO PU ON GPF.CO_PESSOA = PU.CO_PESSOA
LEFT JOIN FIES_REMANESCENTE.TB_REM_INSCRICAO REINS ON PU.CO_USUARIO = REINS.CO_USUARIO
WHERE GPF.NU_CPF = '41545102821';

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO WHERE co_inscricao = 11323830 --CO_USUARIO = 124542;
SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO WHERE co_inscricao = 10868505 --CO_USUARIO = 124542;
SELECT CO_INSCRICAO, CO_USUARIO, TO_CHAR(DT_HISTORICO, 'DD/MM/YYYY HH24:MI:SS'), TP_CHAMADA_OCUPACAO FROM FIES_PREINSCRICAO.th_pre_chamada_ocupacao WHERE CO_usuario = 7890968 ORDER BY DT_HISTORICO DESC;

update FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO set DT_OCUPACAO = SYSDATE  WHERE co_inscricao = 11323830
--auditoria chamada ocupação.update
select co.co_inscricao,co.co_usuario,co.co_semestre,
      case
         when co.tp_usuario = 1 then '1-REGULAR'
         when co.tp_usuario = 2 then '2-REMANESCENTE'
         ELSE '-'
      end TP_USUARIO,
      case
         when co.tp_vaga = 1 then '1-PUBLICO'
         when co.tp_vaga = 2 then '2-P-FIES'
         when co.tp_vaga = 3 then '3-LIMINAR'
         else '-'
      end TP_VAGA,
      case
         when co.tp_chamada_ocupacao = 1 then '1-CHAMADA'
         when co.tp_chamada_ocupacao = 2 then '2-OCUPAÇÃO'
         when co.tp_chamada_ocupacao = 3 then '3-DESOCUPAÇÃO'
         else '-'
      end TP_CHAMADA_OCUPACAO,
      co.*
--from   FIES_PREINSCRICAO.tb_pre_chamada_ocupacao co
from FIES_AUDITORIA.LG_PRE_CHAMADA_OCUPACAO co
where  co.co_usuario = 124542
order  by co.DT_OPERACAO_LOG;

SELECT * FROM FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PRIVADO WHERE CO_USUARIO = 124542;

SELECT * FROM FIES_FINANCIAMENTO.TB_FIN_CANDIDATO_PUBLICO WHERE CO_USUARIO = 7742632;

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER_CURSO WHERE CO_CLUSTER = 25914;

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER_VAGA_PRIVADO WHERE CO_CLUSTER_VAGA_PRIVADO = '0000023533201810119931';

SELECT * FROM FIES_FINANCIAMENTO.TB_FIN_CANDIDATO WHERE CO_INSCRICAO = 10154284;

--  Iniciou a inscrição em 21/02/2018 (Situacao 1-Em preenchimento)
--  Concluiu a inscrição em 22/02/2018 (Situação 2-)
SELECT DS_SITUACAO_INSCRICAO, CO_TIPO_VENCIMENTO, I.* 
FROM FIES_AUDITORIA.LG_PRE_INSCRICAO I 
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_SITUACAO_INSCRICAO SIT ON SIT.CO_SITUACAO_INSCRICAO = I.CO_SITUACAO_INSCRICAO
WHERE CO_INSCRICAO = 10154284;

--  Foi chamado em 28/05/2018 mas não ocupou a vaga
SELECT CO_INSCRICAO, CO_USUARIO, TO_CHAR(DT_HISTORICO, 'DD/MM/YYYY HH24:MI:SS'), TP_CHAMADA_OCUPACAO FROM FIES_PREINSCRICAO.th_pre_chamada_ocupacao WHERE CO_INSCRICAO = 7601785 ORDER BY DT_HISTORICO DESC;

--  Só teve uma opção de curso
SELECT PTF.CO_INSCRICAO,
PTF.NU_OPCAO,
PTF.CO_CURSO,
PTF.CO_TURNO,
PTF.QT_SEMESTRE_CURSO,
PTF.QT_SEMESTRE_CONCLUIDO,
PTF.QT_SEMESTRE_FINANCIAMENTO,
PTF.VL_SEMESTRALIDADE_SEM_DESC,
PTF.VL_SEMESTRALIDADE_FIES
FROM FIES_PREINSCRICAO.TB_PRE_TERMO_FINANCIAMENTO PTF
WHERE CO_INSCRICAO = 10154284 ;

select *  FROM FIES_PREINSCRICAO.TB_PRE_TERMO_FINANCIAMENTO 
--  O curso selecionado foi medicina
SELECT CURSO.NO_CURSO || ' (Cód. ' || CURSO.CO_CURSO,
CAMPUS.NO_CAMPUS || ' (Cód. ' || CAMPUS.CO_CAMPUS,
IES.NO_IES || ' (Cód. ' || IES.CO_IES,
MANTENEDORA.NO_RAZAO_SOCIAL || ' (Cód. ' || MANTENEDORA.CO_MANTENEDORA
FROM FIES_PREINSCRICAO.TB_PRE_CURSO CURSO
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_CAMPUS CAMPUS ON CAMPUS.CO_CAMPUS = CURSO.CO_CAMPUS
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_IES IES ON IES.CO_IES = CAMPUS.CO_IES
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_MANTENEDORA MANTENEDORA ON MANTENEDORA.CO_MANTENEDORA = IES.CO_MANTENEDORA
WHERE CURSO.CO_CURSO = 9772;

--  O curso está vinculado ao cluster 23533
SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER_CURSO WHERE CO_CURSO = 9772;

--  Foram ofertadas 2 vagas no cluster
SELECT * FROM FIES_PREINSCRICAO.tb_pre_curso_oferta_vagas WHERE CO_CURSO = 9772;


--  A classificação dela foi 167 no cluster

SELECT 
ins.CO_INSCRICAO as "CO_INSCRICAO", 
CD.DS_MICRO_REGIAO    AS "Microrregião", 
  AC.NO_AREA_CONHECIMENTO    AS "Área", 
  CD.NO_SUBAREA_CONHECIMENTO AS "Subárea", 
  CD.VL_AVALIACAO            AS "Conceito", 
  C.NU_VAGAS_PUBLICO         AS "Qtde de vagas", 
  NU_CLASSIFICACAO           AS "Classificação", 
  INS.ST_TIPO_CONCORRENCIA   AS "Concorrência", 
  INS.VL_MEDIA_GERAL         AS "Nota no Enem", 
  GPF.NU_CPF                 AS "CPF", 
  GPF.NO_PESSOA              AS "Nome Candidato", 
  CASE 
    WHEN US.TP_USUARIO = 1 
    THEN 'Regular' 
    WHEN US.TP_USUARIO = 2 
    THEN 'Remanescente' 
  END                                         AS "Tipo de Processo", 
  HINS.DT_HISTORICO_INSCRICAO                 AS "Data da Situação", 
case 
    when INS.CO_SITUACAO_INSCRICAO = 1 THEN 'Em preenchimento' 
    when INS.CO_SITUACAO_INSCRICAO = 2 then 'Lista de espera' 
    when INS.CO_SITUACAO_INSCRICAO = 3 then 'Pré-selecionado' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 1 then 'Vencido' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 2 then 'Participação cancelada pelo candidato' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 3 then 'Participação cancelada por não declarar situação acadêmica' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 4 then 'Participação cancelada por não estar matriculado' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 5 then 'Inscrição Postergada'  
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 9 then 'Sem aprovação do agente financeiro' 
    when INS.CO_SITUACAO_INSCRICAO = 4 and INS.co_tipo_vencimento = 10 then 'Rejeitado pela CPSA' 
    when INS.CO_SITUACAO_INSCRICAO = 5 then 'Contratado' 
    when INS.CO_SITUACAO_INSCRICAO = 6 then 'Inscrição Cancelada' 
  END AS "Situação", 
  

  TF.NU_OPCAO                                 AS "Opção", 
  DECODE(CHO.TP_CHAMADA_OCUPACAO, 2, 'X', '') AS "Opção ocupada", 
  TF.CO_CURSO 
  ||'-' 
  || CD.NO_CURSO AS "Curso", 
  CD.DS_TURNO    AS "Turno", 
  CD.CO_CAMPUS 
  ||'-' 
  || CD.NO_CAMPUS AS "Local de Oferta", 
  CD.CO_IES 
  ||'-' 
  || CD.NO_IES AS "IES", 
  CD.CO_MANTENEDORA 
  ||'-' 
  || CD.NO_MANTENEDORA          AS "Mantenedora", 
  INS.CO_SITUACAO_INSCRICAO     AS "Codigo Situação", 
  HCP.CO_SITUACAO_FINANCIAMENTO AS "Codigo Situação Financiamento", 
  FSF.DS_SITUACAO_FINANCIAMENTO AS "Situação Financiamento", 
  HCP.DT_HISTORICO              AS "Data Situação Financiamento", 
  INS.CO_CLUSTER,
  INS.ST_CONCLUIU_ENSINO_SUPERIOR AS "Concluiu Ensino Superior", 
  CASE WHEN INS.TP_CONTRATO_SISFIES = 0 THEN 'Sem contrato'
       when INS.TP_CONTRATO_SISFIES = 1 then 'Contrato encerrado e liquidado' 
       when INS.TP_CONTRATO_SISFIES = 2 then 'Contrato encerrado não liquidado' 
  END AS "Financiamento"
FROM 
  (SELECT INS.CO_INSCRICAO, 
    INS.CO_USUARIO, 
    INS.CO_SEMESTRE, 
    INS.CO_CLUSTER, 
    RANK () OVER (PARTITION BY INS.CO_SEMESTRE, INS.CO_CLUSTER ORDER BY INS.ST_CONCLUIU_ENSINO_SUPERIOR, INS.TP_CONTRATO_SISFIES, INS.VL_MEDIA_GERAL DESC, INS.NU_NOTA_FINAL_RED DESC, INS.NU_NOTA_LINGUAS DESC, INS.NU_NOTA_MATEMATICA DESC, INS.NU_NOTA_CIENCIAS_NATURAIS DESC, INS.NU_NOTA_CIENCIAS_HUMANAS DESC, INS.DT_CADASTRO) NU_CLASSIFICACAO 
  FROM FIES_PREINSCRICAO.TB_PRE_INSCRICAO INS 
  WHERE INS.CO_SEMESTRE = 20181
    

  AND INS.ST_PUBLICO             = 'S' 
  AND INS.CO_SITUACAO_INSCRICAO >= 2 
  AND ins.tp_usuario = 1  
  /* 
  AND EXISTS 
    (SELECT 1 
    FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO PCO 
    WHERE PCO.CO_INSCRICAO       = INS.CO_INSCRICAO 
    --AND CO_CLUSTER_VAGA_PUBLICO IS NOT NULL 
    ) 
  */ 
  ) TA1 

INNER JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO_SEMESTRE US 
ON US.CO_USUARIO   = TA1.CO_USUARIO 
AND US.CO_SEMESTRE = 20181 

INNER JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO U 
ON U.CO_USUARIO = US.CO_USUARIO 
INNER JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA GPF 
ON GPF.CO_PESSOA = U.CO_PESSOA 
INNER JOIN FIES_PREINSCRICAO.TB_PRE_INSCRICAO INS 
ON INS.CO_INSCRICAO = TA1.CO_INSCRICAO 
INNER JOIN FIES_PREINSCRICAO.TB_PRE_HISTORICO_INSCRICAO HINS 
ON HINS.CO_HISTORICO_INSCRICAO = INS.CO_HISTORICO_INSCRICAO 
INNER JOIN FIES_PREINSCRICAO.TB_PRE_SITUACAO_INSCRICAO SINS 
ON SINS.CO_SITUACAO_INSCRICAO = INS.CO_SITUACAO_INSCRICAO 
INNER JOIN FIES_PREINSCRICAO.TB_PRE_TERMO_FINANCIAMENTO TF 
ON TF.CO_INSCRICAO = INS.CO_INSCRICAO 

INNER JOIN FIES_PREINSCRICAO.TB_PRE_CLUSTER_CURSO_DADOS CD 
ON CD.CO_CURSO         = TF.CO_CURSO 
AND CD.CO_TURNO        = TF.CO_TURNO        

AND CD.CO_OFERTA_VAGAS = TF.CO_OFERTA_VAGAS 

LEFT JOIN FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO CHO 
ON CHO.CO_INSCRICAO = TF.CO_INSCRICAO 
AND CHO.CO_CURSO    = TF.CO_CURSO 
AND CHO.CO_TURNO    = TF.CO_TURNO 
LEFT JOIN FIES_FINANCIAMENTO.TB_FIN_CANDIDATO FC 
ON FC.CO_USUARIO   = CHO.CO_USUARIO 
AND FC.CO_SEMESTRE = CHO.CO_SEMESTRE 
AND FC.TP_USUARIO  = CHO.TP_USUARIO 
INNER JOIN FIES_GLOBAL.TB_GLB_SUBAREA_CONHECIMENTO SC 
ON SC.CO_SUBAREA_CONHECIMENTO = CD.CO_SUBAREA_CONHECIMENTO 
INNER JOIN FIES_GLOBAL.TB_GLB_AREA_CONHECIMENTO AC 
ON AC.CO_AREA_CONHECIMENTO = SC.CO_AREA_CONHECIMENTO 
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_TIPO_VENCIMENTO TV 
ON TV.CO_TIPO_VENCIMENTO = INS.CO_TIPO_VENCIMENTO 
INNER JOIN FIES_PREINSCRICAO.TB_PRE_CLUSTER C 
ON C.CO_CLUSTER = TA1.CO_CLUSTER 
LEFT JOIN FIES_FINANCIAMENTO.VW_H_FIN_CANDIDATO_PUBLICO HCP 
ON HCP.CO_CANDIDATO_PUBLICO = FC.CO_USUARIO 
LEFT JOIN FIES_FINANCIAMENTO.TB_FIN_SITUACAO_FINANCIAMENTO FSF 
ON FSF.CO_SITUACAO_FINANCIAMENTO = HCP.CO_SITUACAO_FINANCIAMENTO 
WHERE US.TP_USUARIO              = 1 
--AND CD.CO_UF                     = 43 
--AND CD.CO_MICRO_REGIAO           = 23533 
--and   CD.cO_CURSO              =   106754
--AND CD.NO_CURSO                  = 'MEDICINA' 
--AND CD.VL_AVALIACAO              = 3 
--AND C.CO_CLUSTER = 21122
--and FSF.CO_SITUACAO_FINANCIAMENTO = 5;
AND GPF.NU_CPF = '41545102821';
ORDER BY 1,2,3,4, 
  INS.CO_CLUSTER, 
  6,15,14
  
  -- NOTA EDIÇÕES ENEM
  select * from fies_preinscricao.tb_pre_nota_enem where nu_cpf_aluno = '15268221647';
 
  SELECT DE.*, FI.*
   FROM ODSENEM.dm_inscrito DI
   JOIN ODSENEM.FT_INSCRICAO FI ON FI.CO_DM_INSCRITO = DI.CO_DM_INSCRITO
   JOIN odsenem.DM_EDICAO DE ON DE.CO_DM_EDICAO = DI.CO_DM_EDICAO
  WHERE DI.NU_CPF = '04639653107'
    AND DI.ST_REGISTRO_ATUAL = 1
    AND FI.ST_REGISTRO_ATUAL = 1;
  
  -- RAQUEAMENTO DE INSCRIÇÃO
  SELECT *
  FROM (SELECT  INS.CO_INSCRICAO, INS.CO_USUARIO, INS.CO_SEMESTRE, INS.CO_CLUSTER, INS.ST_CONCLUIU_ENSINO_SUPERIOR AS "NIVEL_SUPERIOR", 
  INS.VL_MEDIA_GERAL  AS "Nota no Enem", --TERMO.CO_CURSO, TERMO.CO_TURNO,
                    RANK ()
                     OVER (PARTITION BY INS.CO_SEMESTRE, INS.CO_CLUSTER
                           ORDER BY INS.ST_CONCLUIU_ENSINO_SUPERIOR,
                             INS.TP_CONTRATO_SISFIES,
                             INS.VL_MEDIA_GERAL DESC,
                             INS.NU_NOTA_FINAL_RED DESC,
                             INS.NU_NOTA_LINGUAS DESC,
                             INS.NU_NOTA_MATEMATICA DESC,
                             INS.NU_NOTA_CIENCIAS_NATURAIS DESC,
                             INS.NU_NOTA_CIENCIAS_HUMANAS DESC,
                             INS.DT_CADASTRO) NU_CLASSIFICACAO
            FROM FIES_PREINSCRICAO.TB_PRE_INSCRICAO INS
            WHERE INS.CO_SEMESTRE = 20191
            AND INS.CO_CLUSTER = 42584
            AND INS.CO_SITUACAO_INSCRICAO >= 2
            AND INS.ST_PUBLICO = 'S')
WHERE CO_CLUSTER = 42584


  
  -- VERIFICAR AS VAGAS QUE FORAM OCUPADAS
select * from fies_preinscricao.tb_pre_chamada_ocupacao where dt_ocupacao is not null and co_inscricao in (7507487,7068144,);

 --  Foram ofertadas  vagas no cluster
SELECT * FROM FIES_PREINSCRICAO.tb_pre_curso_oferta_vagas WHERE co_curso in (4959) and co_semestre = 20191;

-- PERIODO INSCRIÇÕES
SELECT * FROM FIES_PREINSCRICAO.TB_PRE_PARAMETRO_INSCRICAO ORDER BY CO_SEMESTRE;

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_PERIODO_INSCRICAO ORDER BY CO_SEMESTRE;
SELECT * FROM FIES_PREINSCRICAO.TB_PRE_PERIODO_REMANESCENTE ORDER BY CO_SEMESTRE;


   -- CONSULTAR DADOS DA VAGA REMANESCENTE 1°/2017
            SELECT ov.co_ocupacao_vaga, tf.co_oferta_vaga, ov.co_vaga_liberada_curso, ov.dt_ocupacao_vaga, 
              vb.co_controle_vaga_brasil,vb.co_controle_vaga AS vaga_Brasil, cv.co_semestre AS co_semestre_vaga, cv.co_mantenedora, 
              ofv.co_curso, ofv.co_turno, ofv.nu_total_vagas, ofv.st_ativo,cv.nu_vaga, cv.dt_cadastro,
               cv.st_ativo, i.co_semestre, i.co_usuario, cv. * FROM  fies_remanescente.tb_rem_ocupacao_vaga ov 
              LEFT JOIN fies_remanescente.tb_rem_controle_vaga_brasil vb  ON vb.co_controle_vaga = ov.co_controle_vaga
              LEFT JOIN fies_remanescente.tb_rem_termo_financiamento tf ON ov.co_inscricao = tf.co_inscricao
              LEFT JOIN fies_remanescente.tb_rem_inscricao i ON i.co_inscricao = tf.co_inscricao
              LEFT JOIN fies_remanescente.tb_rem_controle_vaga cv ON cv.co_controle_vaga = ov.co_controle_vaga
              LEFT JOIN  fies_remanescente.tb_rem_oferta_vagas ofv ON tf.co_oferta_vaga = ofv.co_oferta_vaga  
            WHERE ov.co_inscricao = 2064907;


--  Estrutura oracle

begin

UPDATE fies_preinscricao.tb_pre_inscricao SET co_situacao_inscricao = 3, co_tipo_vencimento = NULL WHERE co_inscricao = 4834380.;

 

commit;

   EXCEPTION

    WHEN OTHERS THEN BEGIN

        ROLLBACK;

        RAISE;

     end;      

 end;    




--localiza tabela no oracle
select * from ALL_TABLES where TABLE_NAME like '%NOTA%';

--localiza colunas no oracle
SELECT *
FROM   ALL_TAB_COLUMNS
WHERE  --TABLE_NAME LIKE '%CLUSTER%' AND
      COLUMN_NAME LIKE '%NOTA%';

--localiza texto em todos os objetos oracle	  
SELECT *
FROM ALL_SOURCE
WHERE UPPER(TEXT) LIKE '%TEXTO%' 



-- RESETAR SENHA DO USUARIO DA PRÉ-INSCRIÇÃO
update FIES_PREINSCRICAO.TB_PRE_USUARIO

set DS_SENHA = '2ececb1ab149ae5593f1fc263e1294ab6c3d0a9d'

where CO_USUARIO = 2776987;
COMMIT;

-- SIMULACAO NO FIESSELECAO
/*
mamae 

1980
dia 01
mes janeiro
8 
Mec@1234
*/


-- CADASTRO DA LIMINAR NO ORACLE
SELECT
  t0_.CO_LIMINAR      AS CO_LIMINAR_0,
  t1_.CO_TIPO_LIMINAR AS CO_TIPO_LIMINAR_1,
  t2_.CO_ABRANGENCIA  AS CO_ABRANGENCIA_2,
  t3_.CO_PESSOA       AS CO_PESSOA_3,
  t4_.CO_USUARIO      AS CO_USUARIO_4,
  t2_.DT_CADASTRO_ABRANGENCIA
FROM FIES_PREINSCRICAO.TB_PRE_LIMINAR t0_
  INNER JOIN FIES_PREINSCRICAO.TB_PRE_LIMINAR_TIPO_LIMINAR t5_
    ON t0_.CO_LIMINAR = t5_.CO_LIMINAR
  INNER JOIN FIES_PREINSCRICAO.TB_PRE_TIPO_LIMINAR t1_ ON t5_.CO_TIPO_LIMINAR = t1_.CO_TIPO_LIMINAR
  INNER JOIN FIES_PREINSCRICAO.TB_PRE_ABRANGENCIA t2_ ON t0_.CO_LIMINAR = t2_.CO_LIMINAR
  INNER JOIN FIES_GLOBAL.TB_GLB_COMPL_PESSOA_FISICA t6_ ON t2_.CO_COMPL_PESSOA_FISICA = t6_.CO_COMPL_PESSOA_FISICA
  INNER JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA t3_ ON t6_.CO_PESSOA = t3_.CO_PESSOA
  LEFT JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO t4_ ON (t4_.CO_PESSOA = t3_.CO_PESSOA)
WHERE t0_.ST_CONCLUIDO = 'S'
      AND t3_.NU_CPF = '70053984404'
      --AND t5_.CO_TIPO_LIMINAR = ?
      AND t0_.CO_SEMESTRE = 20192
      AND ((sysdate BETWEEN t0_.DT_INICIAL_VIGENCIA AND t0_.DT_FINAL_VIGENCIA) OR t0_.DT_FINAL_VIGENCIA IS NULL)
      AND       t2_.DT_CADASTRO_ABRANGENCIA + 4 >= TO_DATE(TO_CHAR(sysdate, 'DD/MM/YYYY'), 'DD/MM/YYYY');


-- VAGAS OFERTADAS
--CADEIRA DISPONIVEL
SELECT COUNT(1) QT_VAGA_CADEIRA_DISPONIVEL
FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER_CURSO_DETALHE DET
WHERE CO_CLUSTER = 47843
 AND CO_CURSO   = 99476
 AND CO_TURNO   = 10071
 AND TP_VAGA    = 1
 AND NOT EXISTS  (SELECT 1
                   FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO PCO
                  WHERE PCO.CO_CURSO   = DET.CO_CURSO
                    AND PCO.CO_H_CURSO = DET.CO_H_CURSO
                    AND PCO.CO_TURNO   = DET.CO_TURNO
                    AND PCO.NU_LINHA   = DET.NU_LINHA
                  );
                  
--CLUSTER(TICKET)
SELECT COUNT(1) QT_VAGA_DISTRIBUIDA_DISPONIVEL
FROM   FIES_PREINSCRICAO.TB_PRE_CLUSTER_VAGA_PUBLICO PCVP
WHERE  1 = 1
AND    CO_SEMESTRE = 20192
AND    CO_CLUSTER  = 47843
AND NOT EXISTS (SELECT 1
                FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO PCO
                WHERE PCO.CO_CLUSTER_VAGA_PUBLICO = PCVP.CO_CLUSTER_VAGA_PUBLICO                
                );​





-- CONSULTA PRÉ-INSCRICAO
 SELECT 
 PF.NO_PESSOA, PF.NU_CPF, I.CO_SEMESTRE,  C.CO_SEMESTRE_FINANCIAMENTO, I.TP_CONTRATO_SISFIES,I.CO_SITUACAO_INSCRICAO||'-'||ST.DS_SITUACAO_INSCRICAO AS situacao_pre_inscricao,
 I.CO_SITUACAO_INSCRICAO_PV||'-'||     
 CASE 
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 1 THEN 'Em preenchimento'   
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 2 THEN 'Pendente de validacao pelo MEC'
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 3 THEN 'Pre-selecionado'      
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 4 THEN 'Vencido' 
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 5 THEN 'Contratado'
     WHEN I.CO_SITUACAO_INSCRICAO_PV = 6 THEN 'Inscricao cancelada' 
  ELSE '-'     
  END "situacao_pre_inscricao_privado", co_situacao_financiamento||' ('||dt_historico||')' AS situacao_financiamento,                                             
CH.CO_CURSO, CH.CO_TURNO, CH.TP_VAGA, CH.CO_USUARIO, CH.TP_USUARIO, CH.TP_VAGA, CH.TP_CHAMADA_OCUPACAO,
 CH.CO_CLUSTER, CH.DT_OCUPACAO, CH.DT_DESOCUPACAO, C.PC_PROUNI,
 C.DT_INICIO_FINANCIAMENTO,C.DT_FIM_FINANCIAMENTO,C.DT_LIMITE_CPSA, CP.NU_ABA, 
  CO_SITUACAO_FINANCIAMENTO||' ('||DT_HISTORICO||')' AS SITUACAO_FINANCIAMENTO, X. * 
  FROM 
    (
      SELECT * FROM fies_financiamento.th_fin_candidato_publico tch1 
        LEFT JOIN FIES_PREINSCRICAO.TB_PRE_INSCRICAO I ON I.CO_USUARIO = tch1.co_candidato_publico
        LEFT JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO U ON U.CO_USUARIO = I.CO_USUARIO
        LEFT JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA PF ON PF.CO_PESSOA = U.CO_PESSOA
      WHERE PF.NU_CPF IN ('12708890603') 
            ORDER BY tch1.dt_historico desc
    ) X
  LEFT JOIN fies_financiamento.tb_fin_candidato_publico CP ON X.CO_CANDIDATO_PUBLICO = CP.CO_USUARIO 
  LEFT JOIN FIES_PREINSCRICAO.TB_PRE_INSCRICAO I ON CP.CO_USUARIO = I.CO_USUARIO
  LEFT JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO U ON U.CO_USUARIO = I.CO_USUARIO
  LEFT JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA PF ON PF.CO_PESSOA = U.CO_PESSOA
  LEFT JOIN FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO CH ON CH.CO_INSCRICAO = I.CO_INSCRICAO
  LEFT JOIN fies_financiamento.tb_fin_candidato C ON C.CO_USUARIO = I.CO_USUARIO   AND C.CO_INSCRICAO = I.CO_INSCRICAO
  LEFT JOIN FIES_PREINSCRICAO.TB_PRE_SITUACAO_INSCRICAO ST ON  i.co_situacao_inscricao = st.co_situacao_inscricao
  WHERE PF.NU_CPF IN ('12708890603') 
  AND I.CO_SITUACAO_INSCRICAO >=3
  AND CH.DT_OCUPACAO IS NOT NULL  
  AND ROWNUM = 1;




--- CONSULTAR OFERTAS DE VAGAS DA INSCRIÇÃO

-- VERIFICAR AS VAGAS QUE FORAM OCUPADAS

select * from fies_preinscricao.tb_pre_chamada_ocupacao where dt_ocupacao is not null and co_inscricao in (195319878);

 

--  Foram ofertadas  vagas no cluster

SELECT * FROM FIES_PREINSCRICAO.tb_pre_curso_oferta_vagas WHERE co_curso in (78256) and co_semestre = 20192;

 

--OFERTA

SELECT DISTINCT CO_CURSO, CO_TURNO, NU_VAGAS, NU_VAGA_EXTRA FROM FIES_PREINSCRICAO.TB_PRE_CURSO_OFERTA_VAGAS WHERE CO_SEMESTRE = 20192 AND CO_CURSO = 78256;

Vagas 6 + 32 extras.

 

--DISTRIBUICAO POR CLUSTER - TICKET - (VAGAS DISTRIBUIDAS PELO MEC)

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER WHERE CO_SEMESTRE = 20191 AND CO_CLUSTER = 44198;

--PUBLICO: 6

--PRIVADO: 0

 

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER WHERE CO_SEMESTRE = 20191 AND CO_CLUSTER = 44198;

 

--DISTRIBUICAO POR CURSO - CADEIRA - (REFLETE A QUANTIDADE DE VAGAS OFERTADAS)

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CLUSTER_CURSO_DETALHE WHERE CO_CURSO = 1399614 and CO_CLUSTER = 44198;

 

--OCUPACAO

SELECT * FROM FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO WHERE CO_SEMESTRE = 20192 AND CO_CURSO = 78256; TP_CHAMADA_OCUPACAO = 2 AND CO_CLUSTER = 24964 AND CO_CURSO = 1378747;

-- GERAR CHAVE SEGURANÇA FIESSELECAO
CREATE OR REPLACE FUNCTION md5 (valor VARCHAR) RETURN VARCHAR2 IS
   v_input VARCHAR2(2000) := valor;
   hexkey VARCHAR2(32) := NULL;
BEGIN
   hexkey := RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.md5(input => UTL_RAW.cast_to_raw(v_input)));
   RETURN NVL(hexkey,'');
END;

select MD5 (1025659605052020) FROM dual;

    select co_usuario||dt_ocupacao from 
    fies_auditoria.lg_pre_chamada_ocupacao 
    where co_inscricao = 201947837 and 
    dt_ocupacao is not null order by dt_operacao_log DESC

-- ATUALIZAR SENHA DO USUARIO NO ORACLE    

update FIES_PREINSCRICAO.TB_PRE_USUARIO

set DS_SENHA = '2ececb1ab149ae5593f1fc263e1294ab6c3d0a9d'

where CO_USUARIO = 6552019;

 COMMIT;
 
 -- situação do financiamento preinscrição
SELECT
NU_CPF, I.CO_INSCRICAO, I.CO_SEMESTRE, I.TP_USUARIO, PCO.TP_VAGA, 
CO_SITUACAO_INSCRICAO, CO_SITUACAO_FINANCIAMENTO, DT_OCUPACAO, CO_CHAMADA,
DT_DESOCUPACAO, PCO.CO_CURSO, PCO.CO_TURNO, I.CO_CLUSTER
-- PCO.
-- i.
-- tf.
-- c.
-- vw. 
-- *
FROM FIES_PREINSCRICAO.TB_PRE_INSCRICAO I
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_USUARIO U ON U.CO_USUARIO = I.CO_USUARIO
LEFT JOIN FIES_GLOBAL.TB_GLB_PESSOA_FISICA PF ON PF.CO_PESSOA = U.CO_PESSOA
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_TERMO_FINANCIAMENTO TF ON TF.CO_INSCRICAO = I.CO_INSCRICAO
LEFT JOIN FIES_FINANCIAMENTO.TB_FIN_CANDIDATO C ON C.CO_USUARIO = I.CO_USUARIO 
LEFT JOIN FIES_PREINSCRICAO.TB_PRE_CHAMADA_OCUPACAO PCO ON PCO.CO_INSCRICAO = I.CO_INSCRICAO
LEFT JOIN FIES_FINANCIAMENTO.VW_H_FIN_CANDIDATO_PUBLICO VW ON VW.CO_CANDIDATO_PUBLICO = I.CO_USUARIO                                                           
WHERE PF.NU_CPF IN ('12968388460',
'06487944157',
'19072339703',
'12049356455',
'07598107106',
'13798770409',
'01737731509' 
) AND I.CO_SEMESTRE = 20202
AND I.TP_USUARIO = 2
 
-- INSERIR HISTÓRICO DA INSCRIÇAO 

INSERT INTO FIES_PREINSCRICAO.TB_PRE_HISTORICO_INSCRICAO (CO_HISTORICO_INSCRICAO, CO_SITUACAO_INSCRICAO,
CO_INSCRICAO, DT_HISTORICO_INSCRICAO, CO_MOTIVO_CANCELAMENTO, CO_TIPO_VENCIMENTO, NU_ABA)
VALUES (FIES_PREINSCRICAO.SQ_PRE_HISTORICO_INSCRICAO.NEXTVAL,1, 203931453, SYSDATE, NULL, NULL, 0);

ALTER TABLE FIES_PREINSCRICAO.TB_PRE_OFERTA_VAGAS ADD DS_CHAVE_SEGURANCA VARCHAR2(50);



-- APONTAMENTOS NO BANCO PARA VALIDAÇÃO NO FIESSELEÇÃO
UPDATE FIES_SEGURANCA.TB_SPF_SISTEMA
SET DS_URL = 'http://hmg-fiesoferta.mec.gov.br' ,
DS_REDIRECT_URI = 'http://hmg-fiesoferta.mec.gov.br/application/autenticacao/receive-auth-code' ,
ds_redirect_logout = '/application/autenticacao/sair',
DS_REDIRECT_DOCUMENTO = 'http://hmg-fiesoferta.mec.gov.br/vaga/termo/salvar-assinatura'
WHERE CO_SISTEMA = 42;
COMMIT;


UPDATE FIES_SEGURANCA.TB_SPF_SISTEMA
SET DS_URL = 'http://dsv-fiesoferta.mec.gov.br' ,
DS_REDIRECT_URI = 'http://dsv-fiesoferta.mec.gov.br/application/autenticacao/receive-auth-code' ,
ds_redirect_logout = '/application/autenticacao/sair',
DS_REDIRECT_DOCUMENTO = 'http://dsv-fiesoferta.mec.gov.br/vaga/termo/salvar-assinatura'
WHERE CO_SISTEMA = 42;
COMMIT;


UPDATE FIES_SEGURANCA.TB_SPF_SISTEMA
SET DS_URL = 'http://sto-fiesoferta.mec.gov.br' ,
DS_REDIRECT_URI = 'http://sto-fiesoferta.mec.gov.br/application/autenticacao/receive-auth-code' ,
ds_redirect_logout = '/application/autenticacao/sair',
DS_REDIRECT_DOCUMENTO = 'http://sto-fiesoferta.mec.gov.br/vaga/termo/salvar-assinatura'
WHERE CO_SISTEMA = 42;

COMMIT;