BEGIN
 RAISE NOTICE 'INICIO DA TRANSAÇAO!';

DECLARE 
V_CO_INSCRICAO INT := 89322;
V_SEMESTRE_ENCERRA NUMERIC := 12017;
V_ANO SMALLINT := 2017;
V_MES_ENCERRA SMALLINT := 7;
V_TP_ENCERRA CHAR := 'L';
ENCERRADO BIGINT;

BEGIN

SELECT COUNT(*) INTO ENCERRADO FROM INSCRICAO.TB_FIES_ENCERRAMENTO WHERE CO_INSCRICAO = V_CO_INSCRICAO AND CO_SITUACAO_ENCERRAMENTO = 7;

FOR REC IN 
		SELECT I.CO_INSCRICAO , E.CO_INSCRICAO, 
		( SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
		  WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE_ENCERRA ) COD_SEMESTRE, 
		  CASE 
			WHEN I.NU_SEMESTRE_REFERENCIA IN (22015, 12016, 22016, 12017, 22017) THEN 'CONTROLE-VAGA'
			ELSE 'SEM-CONTROLE-VAGA'
		  END ST_VAGA,
		 * FROM INSCRICAO.TB_FIES_INSCRICAO I
		LEFT JOIN INSCRICAO.TB_FIES_ENCERRAMENTO E ON E.CO_INSCRICAO = I.CO_INSCRICAO 
		WHERE I.CO_INSCRICAO = V_CO_INSCRICAO AND CO_SITUACAO_INSCRICAO = 5 AND
		TP_OPCAO_ENCERRAMENTO = V_TP_ENCERRA 
		AND CO_SITUACAO_ENCERRAMENTO != 7
		
		

LOOP 

IF (ENCERRADO = 0) THEN 

  RAISE NOTICE 'ENCERRANDO CONTRATO NO SEMESTRE %', V_SEMESTRE_ENCERRA;

  IF (REC.ST_VAGA = 'CONTROLE-VAGA') THEN 

	  UPDATE INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO SET 
		DT_PRAZO_CONCLUSAO_INSCRICAO = NOW()+10
	  WHERE CO_INSCRICAO = V_CO_INSCRICAO;
  END IF;	  
	  
  UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
	CO_SITUACAO_INSCRICAO = 15
  WHERE CO_INSCRICAO = V_CO_INSCRICAO;

  
INSERT INTO INSCRICAO.TB_FIES_ENCERRAMENTO(
            CO_ENCERRAMENTO, CO_INSCRICAO, CO_SITUACAO_ENCERRAMENTO, CO_SEMESTRE_ADITAMENTO, 
            NU_SEMESTRE_REFERENCIA, NU_MES_ENCERRAMENTO, NU_ANO_ENCERRAMENTO, 
            NU_PRAZO_AMORTIZACAO, TP_ENCERRAMENTO, TP_OPCAO_ENCERRAMENTO, 
            TP_ORIGEM_ENCERRAMENTO, DT_TERMINO_PERIODO_UTILIZACAO, DT_INICIO_FASE_CARENCIA, 
            DT_INICIO_AMORTIZACAO, DT_LIMITE_COMPARECIMENTO_BANCO, DT_LIMITE_RETORNO_AF, 
            DT_INCLUSAO_ENCERRAMENTO, DT_CONFIRMACAO_ENCERRAMENTO, DT_CONCLUSAO_ENCERRAMENTO, 
            DS_CALCULOS_SERIALIZADOS, TP_OPCAO_ENCERRAMENTO_ORIGINAL, DT_TERMINO_PERIODO_UTILIZACAO_ORIGINAL, 
            DT_INICIO_FASE_CARENCIA_ORIGINAL, DT_INICIO_AMORTIZACAO_ORIGINAL, 
            NU_PRAZO_AMORTIZACAO_ORIGINAL, DT_INICIO_COMPARECIMENTO_BANCO, 
            ST_MIGRADO, ST_OBITO_INVALIDEZ, ST_ENCERRAMENTO_TACITO)
    VALUES (NEXTVAL('INSCRICAO.TB_FIES_ENCERRAMENTO_CO_ENCERRAMENTO_SEQ'), V_CO_INSCRICAO, 7, REC.COD_SEMESTRE, 
            V_SEMESTRE_ENCERRA, V_MES_ENCERRA, V_ANO, 
            NULL, -- NU_PRAZO_AMORTIZACAO
             'I', V_TP_ENCERRA, 
            'E', NOW, 
            NULL, -- DT_INICIO_FASE_CARENCIA
            NULL, -- DT_INICIO_AMORTIZACAO
            NULL, -- DT_LIMITE_COMPARECIMENTO_BANCO,
            NULL, -- DT_LIMITE_RETORNO_AF 
            NOW, NOW, NOW, 
            NULL, -- DS_CALCULOS_SERIALIZADOS
            NULL, NULL, 
            NULL, NULL, 
            NULL, 
            NULL, -- DT_INICIO_COMPARECIMENTO_BANCO
            'N', NULL, 'N');
  

ELSE 
   RAISE NOTICE 'JA EXISTE ENCERRAMENTO CONTRATADO';
   
END IF;

RAISE NOTICE 'VALOR(%)', ENCERRADO;

END LOOP;

END; 

COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;
 





 