-- FUNCTION:   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES  (VARCHAR, CHARACTER, NUMERIC, INT)

-- DROP FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR, CHARACTER, NUMERIC, INT);

CREATE OR REPLACE FUNCTION INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (
	P_CPF VARCHAR(11),
	P_SEMESTRE NUMERIC,
	P_ST_INSCRICAO INT
)
  RETURNS VOID AS
$BODY$

/* FUNÇÃO PARA AJUSTAR A SITUAÇÃO DA INSCRIÇÃO NO SISFIES, SEJA AS SITUAÇÕES (5,3,2,1 OU 7)*/

DECLARE 

EXIST_INSC BIGINT;
V_CRL_VAGA BIGINT;
VALIDA_PRE BIGINT;
STATUS_CONTRATADO BIGINT;
V_CO_BANCO CHARACTER(3);
LIMINAR BIGINT;
ANO VARCHAR:= (SUBSTRING (P_SEMESTRE, 2,5));
REC RECORD;

BEGIN 

	SELECT COUNT(*) 
	INTO EXIST_INSC 
	FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF;

	SELECT CO_BANCO 
	INTO V_CO_BANCO 
	FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF;	

	SELECT COUNT(*) 
	INTO LIMINAR 
	FROM INSCRICAO.TB_FIES_ABRANGENCIA_LIMINAR 
	WHERE NU_CPF = P_CPF;	
	
	IF (P_SEMESTRE::INT IN (22015,12016,22016,12017,22017)) THEN

		SELECT COUNT(*) INTO V_CRL_VAGA FROM INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
		WHERE CO_INSCRICAO = (
			SELECT CO_INSCRICAO FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF
		);
		
		SELECT COUNT(*) INTO VALIDA_PRE FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
		WHERE CO_INSCRICAO = (
			SELECT CO_INSCRICAO FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = P_CPF
		) AND 
		ST_ATIVO = TRUE AND CO_PRE_INSCRICAO 
		IS NOT NULL GROUP BY DT_LOG_ALTERACAO LIMIT 1;
	END IF;

		
	IF (V_CO_BANCO = '104') THEN

		SELECT COUNT(*) INTO STATUS_CONTRATADO FROM INTEGRACAO.TB_FIES_IMPORTA_CONTRATO_FIES IMP, 
		INSCRICAO.TB_FIES_INSCRICAO I
		WHERE IMP.CO_CPF = I.NU_CPF AND
		IMP.ST_CONTRATACAO = 'C' AND
		IMP.CO_CPF = P_CPF
		;

	ELSE 
		SELECT COUNT (*) INTO STATUS_CONTRATADO 
		FROM INTEGRACAO.TB_FIES_IMPORTA_CONTRATO_FIES_BB
		WHERE 	NU_CPF = P_CPF AND
		CO_MOTIVO_SITUACAO = '0000'
		AND DS_MOTIVO_SITUACAO IS NULL;
	END IF;

	
FOR REC IN

	SELECT CO_INSCRICAO, CO_SEMESTRE_INSCRICAO, V_CO_SEMESTRE_INSCRICAO, NU_SEMESTRE_REFERENCIA, 
	(ANO||'-'||MES||'-'||DIA) AS V_CONCLUSAO_INSC, PRORROGADO, LG_VALIDACAO  
	FROM (
	
		SELECT
		 NU_SEMESTRE_REFERENCIA, 
		(
		   SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
		   WHERE NU_SEMESTRE_REFERENCIA = I.NU_SEMESTRE_REFERENCIA )CO_SEMESTRE_INSCRICAO,

		 (
		   SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
		   WHERE NU_SEMESTRE_REFERENCIA = P_SEMESTRE)V_CO_SEMESTRE_INSCRICAO,
		 TF.CO_INSCRICAO, DS_SITUACAO_INSCRICAO, 
		 I.NU_CPF, NO_USUARIO, DT_LIMITE_CPSA, DT_LIMITE_CONTRATACAO, 
		 DT_LIMITE_RETORNO_AGENTE_FINANC,DT_CONFIRMACAO_INSCRICAO, 
		(
		   SELECT DT_LOG_ALTERACAO FROM AUDITORIA.VW_LG_FIES_INSCRICAO
		   WHERE CO_INSCRICAO = I.CO_INSCRICAO AND 
		   CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO 
		   ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
		) LG_VALIDACAO, 

		CASE 
			WHEN P.CO_SEMESTRE_ADITAMENTO IS NOT NULL AND 
			P.NU_SEMESTRE_PRORROGADO IS NOT NULL AND
			P.CO_INSCRICAO IS NOT NULL
			THEN 'S' 
			ELSE 
			'N'
		END PRORROGADO,
		DT_CONCLUSAO_INSCRICAO, 
		(SUBSTRING (NU_SEMESTRE_REFERENCIA::VARCHAR, 1, 1)) SEMEST,
		(30::VARCHAR) DIA,
		CASE 
		WHEN SUBSTRING(NU_SEMESTRE_REFERENCIA, 1,1) = '1' THEN '06'
		ELSE 
		'12'
		END MES
			
		FROM  INSCRICAO.TB_FIES_INSCRICAO I
		INNER JOIN INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO TF ON I.CO_INSCRICAO = TF.CO_INSCRICAO
		INNER JOIN INSCRICAO.TB_FIES_USUARIO_INSCRICAO UI ON UI.NU_CPF = I.NU_CPF
		INNER JOIN INSCRICAO.TB_FIES_SITUACAO_INSCRICAO ST USING (CO_SITUACAO_INSCRICAO)
		LEFT JOIN INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA P ON P.CO_INSCRICAO = I.CO_INSCRICAO
		WHERE I.NU_CPF = P_CPF
	)


LOOP 

	IF (EXIST_INSC > 0) THEN 

		IF (REC.V_CO_SEMESTRE_INSCRICAO > REC.CO_SEMESTRE_INSCRICAO) THEN
			RAISE NOTICE 'A INSCRICAO ESTA SENDO POSTERGADA PARA %', P_SEMESTRE;
			
			UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
			NU_SEMESTRE_REFERENCIA = P_SEMESTRE
			WHERE NU_CPF = P_CPF;
					
			IF (REC.PRORROGADO =  'S') THEN
				UPDATE INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA SET
				CO_SEMESTRE_ADITAMENTO = REC.CO_SEMESTRE_INSCRICAO,
				DT_PERGUNTA_INSCRICAO_PRORROGAD = NOW,
				NU_SEMESTRE_PRORROGADO = P_SEMESTRE
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO; 

			ELSE
				INSERT INTO  INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA
				(CO_SEMESTRE_ADITAMENTO, CO_INSCRICAO, CO_PERGUNTA_OPCAO, 
				 CO_USUARIO_SSD, DT_PERGUNTA_INSCRICAO_PRORROGAD,
				 NU_SEMESTRE_PRORROGADO, CO_PRE_INSCRICAO)
				VALUES 
				(REC.CO_SEMESTRE_INSCRICAO, REC.CO_INSCRICAO,
				 25, 2574677, NOW, P_SEMESTRE::NUMERIC, NULL);	
			 END IF;
		END IF;
	

		IF (P_SEMESTRE IN ('22015','12016', '22016', '12017', '22017')) THEN

			IF (V_CRL_VAGA > 0) THEN 

				UPDATE INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO SET
				DT_PRAZO_CONCLUSAO_INSCRICAO = NOW+90
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;
			ELSE 
				INSERT INTO INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INSCRICAO
				SELECT
					    NEXTVAL('INSCRICAO.TB_FIES_CONTROLE_VAGA_PRE_INS_CO_CONTROLE_VAGA_PRE_INSCRICA_SEQ'), 
					    CO_SEMESTRE, CO_MANTENEDORA, 
					    CO_IES, CO_CAMPUS, CO_CURSO, CO_TURNO, UPPER('L')||LOWER('IMINAR'), CO_PRE_INSCRICAO, 
					    NOW(), NOW()+90, CO_INSCRICAO, 
					    TRUE, CO_REM_INSCRICAO, NULL
				 FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
				ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1;
			END IF;

			IF (VALIDA_PRE > 0) THEN 
				RAISE NOTICE 'VAGA DA PRE-INSCRICAO PROCESSO REGULAR';
				
				UPDATE FIES_PREINSCRICAO.TB_PRE_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = 3, 
				CO_TIPO_VENCIMENTO = NULL 
				WHERE CO_INSCRICAO::INT = (					
					SELECT CO_PRE_INSCRICAO::INT FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
					WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
					ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
				);
			ELSE
				RAISE NOTICE 'VAGA DA PRE-INSCRICAO PROCESSO REMANSCENTE';
				UPDATE FIES_REMANESCENTE.TB_REM_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = 3, 
				CO_TIPO_VENCIMENTO = NULL 
				WHERE CO_INSCRICAO::INT = (					
					SELECT CO_REM_INSCRICAO::INT FROM AUDITORIA.VW_LG_FIES_CONTROLE_VAGA_PRE_INSCRICAO 
					WHERE CO_INSCRICAO = REC.CO_INSCRICAO AND 
					ST_ATIVO = TRUE ORDER BY DT_LOG_ALTERACAO DESC LIMIT 1
				);

				INSERT INTO  INSCRICAO.TB_FIES_PERGUNTA_INSC_PRORROGA
				(CO_SEMESTRE_ADITAMENTO, CO_INSCRICAO, CO_PERGUNTA_OPCAO, 
				CO_USUARIO_SSD, DT_PERGUNTA_INSCRICAO_PRORROGAD,
				NU_SEMESTRE_PRORROGADO, CO_PRE_INSCRICAO)
				VALUES 
				(REC.CO_SEMESTRE_INSCRICAO, REC.CO_INSCRICAO, 25, 2574677, NOW, P_SEMESTRE::NUMERIC, NULL);
								
			END IF;
		END IF;

		CASE 
			WHEN (P_ST_INSCRICAO  IN (1,2,7) ) THEN
			
				IF (P_ST_INSCRICAO = 1) THEN
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "EM PREENCIMENTO (%)"', P_ST_INSCRICAO;
				END IF;
				
				IF (P_ST_INSCRICAO = 2) THEN 
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "PENDENTE DE VALIDAÇAO PELA CPSA (%)"', P_ST_INSCRICAO;
				END IF;
				
				IF (P_ST_INSCRICAO = 7) THEN 
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "REABERTO PARA CORREÇAO (%)"', P_ST_INSCRICAO;

				END IF;

				UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET
				DT_LIMITE_CPSA = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				DT_CONFIRMACAO_INSCRICAO = NOW
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				IF (LIMINAR > 0)  THEN

					RAISE NOTICE 'PRORROGANDO OS PRAZOS DA LIMINAR (%)', LIMINAR;
					
					UPDATE INSCRICAO.TB_FIES_LIMINAR SET 
					DT_FIM_VALIDADE = NOW+60
					WHERE CO_LIMINAR IN (
						SELECT CO_LIMINAR FROM INSCRICAO.TB_FIES_ABRANGENCIA_LIMINAR
						WHERE NU_CPF = P_CPF
					);

				ELSE 
					RAISE NOTICE 'SEM LIMINAR NA INSCRIÇAO (SISFIES)';
					

				END IF;
				
			WHEN (P_ST_INSCRICAO = 3) THEN
				RAISE NOTICE 'SITUACAO VALIDADO PELA CPSA';

				-- EXCLUIR COMPROVANTES
				DELETE INSCRICAO.TB_FIES_COMPROVANTE WHERE CO_INSCRICAO = REC.CO_INSCRICAO; 


				UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
				CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;
				
				UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET
				DT_LIMITE_CONTRATACAO = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,10),
				DT_LIMITE_RETORNO_AGENTE_FINANC = INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE,15),
				DT_CONFIRMACAO_INSCRICAO = NOW,
				DT_VALIDACAO_CPSA = NOW,
				DT_CONCLUSAO_INSCRICAO = REC.V_CONCLUSAO_INSC::DATE
				WHERE CO_INSCRICAO = REC.CO_INSCRICAO;

				IF (REC.V_CO_SEMESTRE_INSCRICAO < REC.CO_SEMESTRE_INSCRICAO) THEN
					RAISE NOTICE 'O SEMESTRE DA INSCRIÇAO SERA RETROAGIDO DE % PARA % (GAMBIARRA ALTORIZADA PELO FNDE) ...', REC.NU_SEMESTRE_REFERENCIA, P_SEMESTRE;
					UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
						NU_SEMESTRE_REFERENCIA = P_SEMESTRE
					WHERE NU_CPF = P_CPF;		
				END IF;
				
			WHEN (P_ST_INSCRICAO = 5) THEN

				IF (STATUS_CONTRATADO > 0) THEN

				
					RAISE NOTICE 'ALTERANDO A SITUAÇAO DA INSCRIÇAO PARA "CONTRATADO (%)"', P_ST_INSCRICAO;    
					  
					UPDATE INSCRICAO.TB_FIES_INSCRICAO SET 
					CO_SITUACAO_INSCRICAO = P_ST_INSCRICAO  
					WHERE NU_CPF = P_CPF;   

					PERFORM  CONSULTA.FN_FIES_PROCESSAMENTO_VALA(
					    REC.CO_INSCRICAO,'N', NULL);
				ELSE 


					RAISE NOTICE 'NÃO FOI LOCALIZADO O ARQUIVO DA CONTRATAÇÃO DA INSCRIÇÃO DO AGENTE FINANCEIRO (%)', V_CO_BANCO;
				END IF;
				
			ELSE 

				RAISE NOTICE '(ERRO) ALTERAÇOES NAO REALIZADAS PARA ESTE TIPO DE SITUAÇAO DA INSCRIÇAO (%)', P_ST_INSCRICAO;   
			
		END CASE;
	ELSE 
		RAISE NOTICE 'NAO EXISTE INSCRIÇAO NA BASE DE DADOS DO SISFIES';
	END IF;

END LOOP;

END;
$BODY$
  LANGUAGE PLPGSQL VOLATILE
  COST 100;
ALTER FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT)
  OWNER TO ENTERPRISEDB;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO DB_SRV_NOTURNO_FIES;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO SYSDBPOWERCENTER;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO RENATOMACHADO;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO RO_SYSDBFIES_DML;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO RO_NOC_DML;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO ENTERPRISEDB;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO RO_SYSDBFIES_SUSTENTACAO_DDL;
GRANT EXECUTE ON FUNCTION   INSCRICAO.FN_FIES_ALTERA_INSCRICAO_SISFIES (VARCHAR(11), NUMERIC, INT) TO PUBLIC;

