-- INSERIR SUSPENSAO
declare

V_SEMESTRE NUMERIC := 22019;                    -- SEMESTRE E ANO DA SUSPENSÃO
V_ANO SMALLINT := 2019;                          -- ANO DE REALIZAÇÃO DA  SUSPENSÃO
V_MES SMALLINT := 7;                             -- SE FOR O PRIMEIRO SEMESTRE (1) || SE FOR O SEGUNDO SEMESTRE (7)
V_CPF VARCHAR := '06589423440';                 -- CPF DO ESTUDANTE

BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

SELECT NU_SEMESTRE_REFERENCIA INTO V_SEMESTRE FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE;
SELECT NU_MES_SUSPENSAO INTO V_MES FROM INSCRICAO.TB_FIES_SUSPENSAO WHERE NU_MES_SUSPENSAO = V_MES AND NU_SEMESTRE_REFERENCIA = V_SEMESTRE LIMIT 1;
SELECT NU_ANO_SUSPENSAO INTO V_ANO FROM INSCRICAO.TB_FIES_SUSPENSAO WHERE NU_ANO_SUSPENSAO = V_ANO AND NU_SEMESTRE_REFERENCIA = V_SEMESTRE LIMIT 1;
SELECT NU_CPF INTO V_CPF FROM INSCRICAO.TB_FIES_INSCRICAO WHERE NU_CPF = V_CPF;


INSERT INTO INSCRICAO.TB_FIES_SUSPENSAO (CO_INSCRICAO, CO_SITUACAO_SUSPENSAO, CO_SEMESTRE_ADITAMENTO, NU_SEMESTRE_REFERENCIA, NU_MES_SUSPENSAO, NU_ANO_SUSPENSAO, TP_SUSPENSAO,

 DS_MOTIVO_REJEICAO, DT_INCLUSAO_SUSPENSAO, DT_CONFIRMACAO_SUSPENSAO, DT_VALIDACAO_CPSA, DT_LIMITE_RETORNO_AF, DT_CONFIRMACAO_AF, DT_LIMITE_CPSA,

 CO_CURSO, CO_TURNO, CO_MANTENEDORA, CO_IES, CO_CAMPUS, SG_UF, CO_MUNICIPIO, NU_MATRICULA, QT_SEMESTRE_CONCLUIDO, QT_SEMESTRES_CURSO_DESTINO,

 QT_SEMESTRE_FINANCIAMENTO, ST_BOLSISTA_PROUNI, NU_PERCENTUAL_PROUNI, CO_OCUPACAO, CO_ESTADO_CIVIL, NU_CPF_CONJUGE, NO_CONJUGE, CO_CIDADE,

 CO_UF, DS_LOGRADOURO, DS_LOGRADOURO_COMP, DS_BAIRRO, DS_NUMERO, NU_CEP, NU_DDD_TELEFONE_RESIDENCIAL, NU_TELEFONE_RESIDENCIAL,

  NU_DDD_TELEFONE_CELULAR, NU_TELEFONE_CELULAR, NU_RIC, DT_LIMITE_CONTRATACAO, CO_USUARIO_SSD, ST_MIGRADO )

(

                SELECT --TER.*

                               INS.CO_INSCRICAO, 4, 
                                ( SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE),
                                    V_SEMESTRE,V_MES, V_ANO, 'I', NULL,

                               NOW(), NOW(), NOW(), INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE, 10), NULL, NOW(),

                               CUR.CO_CURSO, CUR.CO_TURNO, CUR.CO_MANTENEDORA, CUR.CO_IES, CUR.CO_CAMPUS, CUR.SG_UF, CUR.CO_MUNICIPIO,

                               TER.NU_MATRICULA, TER.QT_SEMESTRE_CONCLUIDO, TER.QT_SEMESTRES_CURSO, TER.QT_SEMESTRE_FINANCIAMENTO,

                                INS.ST_BOLSISTA_PROUNI, INS.NU_PERCENTUAL_PROUNI, INS.CO_OCUPACAO, INS.CO_ESTADO_CIVIL, INS.NU_CPF_CONJUGE, INS.NO_CONJUGE, INS.CO_CIDADE, INS.CO_UF,

                               INS.DS_LOGRADOURO, INS.DS_LOGRADOURO_COMP, INS.DS_BAIRRO, INS.DS_NUMERO, INS.NU_CEP, INS.NU_DDD_TELEFONE_RESIDENCIAL, INS.NU_TELEFONE_RESIDENCIAL, INS.NU_DDD_TELEFONE_CELULAR,

                               INS.NU_TELEFONE_CELULAR, INS.NU_RIC, INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW()::DATE, 15), INS.CO_USUARIO_SSD, 'S'                       

                FROM

                               INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO TER

                               INNER JOIN INSCRICAO.TB_FIES_INSCRICAO INS USING (CO_INSCRICAO)

                               INNER JOIN INSCRICAO.TB_FIES_USUARIO_INSCRICAO USU USING (NU_CPF)

                               INNER JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO CUR USING (CO_CURSO_ASSOCIADO)

                WHERE INS.NU_CPF = V_CPF );

 
commit;
raise notice 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
exception when others then
        rollback;
        raise notice 'ROLLBACK aplicado!!!!!!!!!!';
        raise exception '% %', SQLERRM, SQLSTATE;
end;