
BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

DECLARE 

V_CPF VARCHAR := '63921600278';
V_SEMESTRE_TRANSFERENCIA NUMERIC := '2019';
--V_NUM_MATRICULA VARCHAR := '';
V_QT_SEMESTRE_FINANCIAMENTO INT := 20;
V_QT_SEMESTRE_CONCLUIDO INT := 0;
V_DT_DESLIGAMENTO_IES DATE := '2018-06-30';
V_CO_IES INT := 1917;
V_CO_CURSO INT := 98409;
V_CO_MANTENEDORA INT := 1262;
V_CO_CAMPUS INT :=  658870; 
V_CO_TURNO INT := 10071;
REG_ADITAMENTO BIGINT;
V_CO_ADITAMENTO INT;
V_CO_CURSO_ASSOCIADO_ADITAMENTO INT;

BEGIN

SELECT COUNT(*) INTO REG_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO A
LEFT JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO CA
ON CA.CO_ADITAMENTO = A.CO_ADITAMENTO
WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE_TRANSFERENCIA
AND A.NU_CPF = V_CPF 
AND CO_FINALIDADE_ADITAMENTO = 3;


FOR X IN

SELECT
NU_SEMESTRE_REFERENCIA, CO_SEMESTRE_ADITAMENTO AS CO_SEMESTRE_ADITAMENTO_REFERENCIA, 
 ( 
   SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO 
   WHERE NU_SEMESTRE_REFERENCIA = V_SEMESTRE_TRANSFERENCIA
 ) CO_SEMESTRE_TRANSFERENCIA,
 CO_SITUACAO_ADITAMENTO, V_DT_DESLIGAMENTO_IES, 
 CA.SG_UF, DS_CONDICAO_FUNCIONAMENTO,
 (
     SELECT ST_VINCULO_ATIVO_EMEC FROM VW_FIES_CURSO WHERE 
     CO_MANTENEDORA = V_CO_MANTENEDORA  AND
     CO_IES = V_CO_IES AND
     CO_CURSO = V_CO_CURSO AND 
     CO_CAMPUS = V_CO_CAMPUS AND 
     CO_TURNO = V_CO_TURNO AND 
     DT_PERDA_VINCULO_EMEC ISNULL 
     AND DS_CONDICAO_FUNCIONAMENTO = 'EM ATIVIDADE' LIMIT 1
  ) AS CONDICAO,

 (   
     SELECT SG_UF FROM 
     VW_FIES_CURSO
     WHERE CO_MANTENEDORA = V_CO_MANTENEDORA  AND
     CO_IES = V_CO_IES AND
     CO_CURSO = V_CO_CURSO AND 
     CO_CAMPUS = V_CO_CAMPUS AND 
     CO_TURNO = V_CO_TURNO LIMIT 1
  ) AS UF_MUNICIPIO, 

CA.CO_MUNICIPIO, 
 (
     SELECT CO_MUNICIPIO FROM 
     VW_FIES_CURSO 
     WHERE V_CO_MANTENEDORA = V_CO_MANTENEDORA  AND
     CO_IES = V_CO_IES AND
     CO_CURSO = V_CO_CURSO AND 
     CO_CAMPUS = V_CO_CAMPUS AND 
     CO_TURNO = V_CO_TURNO LIMIT 1
  ) AS COD_MUNICIPIO,  

CO_FINALIDADE_ADITAMENTO, 
QT_SEMESTRES_CURSO_DESTINO, TM.CO_MANTENEDORA_CEDENTE, V_CO_MANTENEDORA, 

* FROM INSCRICAO.TB_FIES_ADITAMENTO A
LEFT JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO CA ON CA.NU_CPF = A.NU_CPF
LEFT JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO CAD ON CAD.CO_ADITAMENTO = A.CO_ADITAMENTO
LEFT JOIN INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO TF ON TF.CO_INSCRICAO = A.CO_INSCRICAO
LEFT JOIN INSCRICAO.TB_FIES_ADITAMENTO_TROCA_MANTENCA TM ON TM.CO_ADITAMENTO = A.CO_ADITAMENTO
LEFT JOIN VW_FIES_CURSO VW ON VW.CO_CURSO = V_CO_CURSO AND
VW.CO_TURNO = V_CO_TURNO AND
VW.CO_IES = V_CO_IES AND
VW.CO_CAMPUS = V_CO_CAMPUS AND
VW.CO_MANTENEDORA = V_CO_MANTENEDORA 
WHERE A.CO_ADITAMENTO = 
 ( SELECT CO_ADITAMENTO FROM INSCRICAO.TB_FIES_ADITAMENTO 
   WHERE NU_CPF = CAD.NU_CPF AND
     CO_SITUACAO_ADITAMENTO = 49 
     ORDER BY CO_SEMESTRE_ADITAMENTO DESC LIMIT 1
   )
 AND 
 VW.ST_VINCULO_ATIVO_EMEC = 
 (
     SELECT ST_VINCULO_ATIVO_EMEC FROM VW_FIES_CURSO WHERE 
     CO_MANTENEDORA = V_CO_MANTENEDORA AND
     CO_IES = V_CO_IES AND
     CO_CURSO = V_CO_CURSO AND 
     CO_CAMPUS = V_CO_CAMPUS AND 
     CO_TURNO = V_CO_TURNO AND 
     DT_PERDA_VINCULO_EMEC ISNULL 
     AND DS_CONDICAO_FUNCIONAMENTO = 'EM ATIVIDADE' LIMIT 1
  )
  AND 
 A.NU_CPF = V_CPF 


LOOP 

IF (REG_ADITAMENTO > 0) THEN
	
	RAISE NOTICE 'O ADITAMENTO NAO PODE SER INSERIDO, POIS JA EXISTE ADITAMENTO DE TRANSFERENCIA DE %', V_SEMESTRE_TRANSFERENCIA;
	
else  
	
	INSERT INTO INSCRICAO.TB_FIES_ADITAMENTO
	SELECT
	NEXTVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ'), CO_INSCRICAO, X.CO_SEMESTRE_TRANSFERENCIA, 
	54, -- SITUAçAO DO ADITAMENTO (PENDENTE PELA CPSA DE DESTINO)
	3, 'S', INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 10), 
	NULL, --INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 15), --DT_LIMITE_COMPARECIMENTO_BANCO
	NULL, --INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 20), --DT_LIMITE_RETORNO_AF
	NOW(), 
	NU_CPF, ST_BOLSISTA_PROUNI,
	NU_PERCENTUAL_PROUNI, NU_RG, DS_ORGAO_EMISSOR, DT_EMISSAO, CO_OCUPACAO,
	CO_ESTADO_CIVIL, NU_CPF_CONJUGE, NO_CONJUGE, VL_RENDA_FAMILIAR_BRUTA_MENSAL,
	VL_RENDA_PESSOAL_BRUTA_MENSAL, CO_CIDADE, CO_UF, DS_LOGRADOURO,
	DS_LOGRADOURO_COMP, DS_BAIRRO, DS_NUMERO, NU_CEP, NU_DDD_TELEFONE_RESIDENCIAL,
	NU_TELEFONE_RESIDENCIAL, NU_DDD_TELEFONE_CELULAR, NU_TELEFONE_CELULAR,
	SG_RACA_COR, ST_DEFICIENCIA, CO_TIPO_DEFICIENCIA, V_SEMESTRE_TRANSFERENCIA,
	CO_CURSO_ASSOCIADO_ADITAMENTO, VL_TAXA_JUROS_ANUAL, NU_MATRICULA, 
	VL_SEMESTRE_SEM_DESCONTO, VL_SEMESTRE_COM_DESCONTO, V_QT_SEMESTRE_CONCLUIDO, 
	VL_RENDA_PER_CAPITA, NU_PERCENTUAL_COMPROMETIMENTO, QT_MESES_FINANC_SEMESTRE_ATUAL,
	NU_PERCENT_SOLICITADO_FINANC, ST_FINANCIAR_INTEGRALIDADE_SEMESTRE,
	CO_TIPO_PERIODICIDADE, QT_PERIODICIDADE, VL_FINANCIAMENTO_EXERCICIO,
	VL_FINANCIAMENTO_GLOBAL, NOW(), V_CO_MANTENEDORA, VL_FINANCIADO_SEMESTRE,
	VL_SEMESTRE_ATUAL, VL_SALDO_AUMENTO_SEMESTRALIDADE, VL_LIMITE_GLOBAL,
	NULL, NULL, CO_MOTIVO_REJEICAO,
	DS_JUSTIFICATIVA_VALIDACAO, CO_USUARIO_INSCRICAO, ST_APROVEITAMENTO_ACADEMICO,
	NU_RIC, V_QT_SEMESTRE_FINANCIAMENTO, -- QT_SEMESTRE_FINANCIAMENTO
	NOW(), ST_PASSO_ADITAMENTO,TP_ORIGEM_FINANCIAMENTO_GLOBAL, VL_GLOBAL_FGEDUC, 
	DT_INICIO_COMPARECIMENTO_BANCO, CO_ORIGEM_DS_BAIRRO, ST_APROVACAO_ALUNO, NOW(),
	CO_CURSO_ASSOCIADO_ADITAMENTO,
	'C',
	NULL, --DT_VALIDACAO_CPSA_DESTINO
	INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 10), --DT_LIMITE_CPSA_DESTINO
	V_DT_DESLIGAMENTO_IES, -- DT_DESLIGAMENTO 
	QT_SEMESTRES_CURSO_DESTINO,
	QT_SEMESTRES_CURSO_ORIGEM, NU_PERCENT_SOLICITADO_FINANC_ORIGINAL,
	'N', NU_CONSULTAS_RECEITA, DT_ULTIMA_CONSULTA_RECEITA,
	CO_USUARIO_SSD, ST_MIGRADO, ST_TROCA_FIANCA, CO_TIPO_FIANCA,
	ST_ALTERACAO_BOLSA_PROUNI, ST_ELEVACAO_PERC_PROUNI, ST_DIREITO_TROCA_FIANCA,
	ST_DADOS_ATUALIZADOS,
	ST_ADITAMENTO_PRELIMINAR, VL_ULTRAPASSADO_MARGEM_PRELIMINAR, VL_AUTORIZADO_AJUSTE, VL_FINANCIADO_PRELIMINAR, DT_VALIDACAO_PRELIMINAR,
	CO_TIPO_PRELIMINAR, V_QT_SEMESTRE_CONCLUIDO+1, -- NU_SEMESTRE_A_CURSAR
	VL_SEMESTRALIDADE_PARA_FIES, CO_ORGAO_EXPEDIDOR, SG_UF_EXPEDIDOR, ST_ENVIA_AF
	FROM INSCRICAO.TB_FIES_ADITAMENTO
	WHERE CO_ADITAMENTO = X.CO_ADITAMENTO AND NU_CPF = V_CPF
	RETURNING CO_ADITAMENTO INTO V_CO_ADITAMENTO;

	INSERT INTO INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
	SELECT 
	NEXTVAL('INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITA_CO_CURSO_ASSOCIADO_ADITAMENTO_SEQ'), 
	V_CPF, 
	V_CO_CURSO, -- CO_CURSO
	V_CO_TURNO, -- CO_TURNO
	V_CO_MANTENEDORA, -- CO_MANTENEDORA
	V_CO_IES, -- CO_IES
	V_CO_CAMPUS, -- CO_CAMPUS
	X.UF_MUNICIPIO , -- SG_UF
	X.COD_MUNICIPIO, -- CO_MUNICIPIO
	NOW(), CO_USUARIO_INSCRICAO,
	(V_QT_SEMESTRE_FINANCIAMENTO - V_QT_SEMESTRE_CONCLUIDO), -- QT_SEMESTRE_FINANCIAMENTO_DESTINO
	V_QT_SEMESTRE_CONCLUIDO, -- QT_SEMESTRE_ADITAMENTO_UTILIZADO
	V_CO_ADITAMENTO -- CO_ADITAMENTO
	FROM INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
	WHERE CO_ADITAMENTO = X.CO_ADITAMENTO
	RETURNING CO_CURSO_ASSOCIADO_ADITAMENTO  INTO V_CO_CURSO_ASSOCIADO_ADITAMENTO;

	UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET 
	CO_CURSO_ASSOCIADO_ADITAMENTO = V_CO_CURSO_ASSOCIADO_ADITAMENTO 
	WHERE CO_ADITAMENTO = V_CO_ADITAMENTO;

	UPDATE INSCRICAO.TB_FIES_CURSO_ASSOCIADO SET 
	CO_MANTENEDORA = V_CO_MANTENEDORA, 
	CO_IES = V_CO_IES, 
	CO_CURSO = V_CO_CURSO, 
	CO_CAMPUS = V_CO_CAMPUS, 
	CO_TURNO = V_CO_TURNO, 
	CO_MUNICIPIO = X.CO_MUNICIPIO, 
	VL_AVALIACAO_ENADE = X.VL_AVALIACAO_ENADE
	WHERE NU_CPF = V_CPF;

	UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET 
	QT_SEMESTRE_CONCLUIDO = V_QT_SEMESTRE_CONCLUIDO, 
	CO_MANTENEDORA = V_CO_MANTENEDORA, 
	QT_SEMESTRE_FINANCIAMENTO = V_QT_SEMESTRE_FINANCIAMENTO
	WHERE CO_INSCRICAO = X.CO_INSCRICAO;

	RAISE NOTICE 'ADITAMENTO DE TRANSFERENCIA INSERIDO COM SUCESSO!!!';
END IF;

END LOOP;
END;

COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;