
BEGIN
RAISE NOTICE 'INICIO DA TRANSACAO.';

DECLARE 

P_CO_INSCRICAO INT := 268747;
P_SEMESTRE_TRANSFERENCIA NUMERIC := '22019';
P_QT_SEMESTRE_FINANCIAMENTO INT := 20;
P_QT_SEMESTRE_CONCLUIDO INT := 8;
P_DT_DESLIGAMENTO_IES DATE;
P_CO_IES INT := 1917;
P_CO_CURSO INT := 98409;
P_CO_MANTENEDORA INT := 1262;
P_CO_CAMPUS INT :=  658870; 
P_CO_TURNO INT := 10071;

V_SEMESTRES_A_SEREM_CURSADOS INT;
V_REG_ADITAMENTO INT;
V_CO_ADITAMENTO INT;
V_CO_CURSO_ASSOCIADO_ADITAMENTO INT;
V_ST_CURSO INT;
X RECORD;

BEGIN

SELECT
 COUNT(*)::INT INTO V_REG_ADITAMENTO 
FROM INSCRICAO.TB_FIES_ADITAMENTO A
LEFT JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO CA
ON CA.CO_ADITAMENTO = A.CO_ADITAMENTO
WHERE NU_SEMESTRE_REFERENCIA = P_SEMESTRE_TRANSFERENCIA AND 
A.CO_INSCRICAO = P_CO_INSCRICAO;

SELECT COUNT(*) INTO V_ST_CURSO 
FROM VW_FIES_CURSO WHERE 
CO_CURSO = P_CO_CURSO AND 
CO_IES = P_CO_IES AND
CO_TURNO = P_CO_TURNO AND
CO_MANTENEDORA = P_CO_MANTENEDORA AND
DS_CONDICAO_FUNCIONAMENTO LIKE LOWER('%ATIVIDADE') AND 
DT_PERDA_VINCULO_EMEC ISNULL; 


FOR X IN

	SELECT DISTINCT ADITAMENTO.NU_SEMESTRE_REFERENCIA, ADITAMENTO.CO_ADITAMENTO
                        ,INSCRICAO.CO_BANCO::NUMERIC, *
                    FROM INSCRICAO.TB_FIES_ADITAMENTO ADITAMENTO
                   INNER JOIN INSCRICAO.TB_FIES_INSCRICAO INSCRICAO
                      ON ADITAMENTO.CO_INSCRICAO = INSCRICAO.CO_INSCRICAO
                   INNER JOIN INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO TERMO ON INSCRICAO.CO_INSCRICAO = TERMO.CO_INSCRICAO                      
                   INNER JOIN INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO CURSO_ASSOCIADO
                      ON ADITAMENTO.CO_CURSO_ASSOCIADO_ADITAMENTO = CURSO_ASSOCIADO.CO_CURSO_ASSOCIADO_ADITAMENTO
                   INNER JOIN PUBLIC.VW_FIES_CURSO CURSO
                      ON CURSO_ASSOCIADO.CO_CURSO = CURSO.CO_CURSO
                      AND CURSO_ASSOCIADO.CO_IES = CURSO.CO_IES 
                     AND CURSO_ASSOCIADO.CO_TURNO = CURSO.CO_TURNO
                     AND CURSO_ASSOCIADO.CO_CAMPUS = CURSO.CO_CAMPUS
                     AND CURSO_ASSOCIADO.CO_MANTENEDORA = CURSO.CO_MANTENEDORA 
        WHERE ADITAMENTO.CO_SITUACAO_ADITAMENTO = 49 
        AND ADITAMENTO.CO_INSCRICAO = P_CO_INSCRICAO
        ORDER BY ADITAMENTO.CO_SEMESTRE_ADITAMENTO DESC LIMIT 1

LOOP 

CASE 

	WHEN (V_REG_ADITAMENTO = 1) THEN 
		RAISE NOTICE '(ERRO) NAO FOI POSSIVEL INSERIR A TRANSFERENCIA, MOTIVO: JA EXISTE TRANSFERENCIA PARA ESTE SEMESTRE DE %', P_SEMESTRE_TRANSFERENCIA;
		ROLLBACK;
		RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
		
	WHEN (V_REG_ADITAMENTO = 0 AND V_ST_CURSO < 1) THEN 
		RAISE NOTICE '(ERRO) NAO FOI POSSIVEL INSERIR A TRANSFERENCIA, MOTIVO: CURSO NAO HABILITADO AO EMEC OU NAO ESTA PRESENTE NA VW_FIES_CURSO' ;
		ROLLBACK;
		RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';

	WHEN (V_REG_ADITAMENTO = 0 AND V_ST_CURSO >= 1) THEN

		V_SEMESTRES_A_SEREM_CURSADOS :=  P_QT_SEMESTRE_FINANCIAMENTO - P_QT_SEMESTRE_CONCLUIDO;

		IF (SUBSTRING(P_SEMESTRE_TRANSFERENCIA,1,1) = 1) THEN
			
			P_DT_DESLIGAMENTO_IES := ((SUBSTRING(P_SEMESTRE_TRANSFERENCIA,2,5))||'-06-30');
		END IF;
			
		IF (SUBSTRING(P_SEMESTRE_TRANSFERENCIA,1,1) = 2) THEN
			P_DT_DESLIGAMENTO_IES := ((SUBSTRING(P_SEMESTRE_TRANSFERENCIA,2,5))||'-12-30');

		END IF;	
				
		INSERT INTO INSCRICAO.TB_FIES_ADITAMENTO
		SELECT
		NEXTVAL('INSCRICAO.TB_FIES_ADITAMENTO_CO_ADITAMENTO_SEQ'), CO_INSCRICAO, 
		(SELECT CO_SEMESTRE_ADITAMENTO FROM INSCRICAO.TB_FIES_SEMESTRE_ADITAMENTO WHERE NU_SEMESTRE_REFERENCIA = P_SEMESTRE_TRANSFERENCIA), 
		54, -- SITUAçAO DO ADITAMENTO (PENDENTE PELA CPSA DE DESTINO)
		3, 'S', INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 10), 
		NULL, --INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 15), --DT_LIMITE_COMPARECIMENTO_BANCO
		NULL, --INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 20), --DT_LIMITE_RETORNO_AF
		NOW(), 
		NU_CPF, ST_BOLSISTA_PROUNI,
		NU_PERCENTUAL_PROUNI, NU_RG, DS_ORGAO_EMISSOR, DT_EMISSAO, CO_OCUPACAO,
		CO_ESTADO_CIVIL, NU_CPF_CONJUGE, NO_CONJUGE, VL_RENDA_FAMILIAR_BRUTA_MENSAL,
		VL_RENDA_PESSOAL_BRUTA_MENSAL, CO_CIDADE, CO_UF, DS_LOGRADOURO,
		DS_LOGRADOURO_COMP, DS_BAIRRO, DS_NUMERO, NU_CEP, NU_DDD_TELEFONE_RESIDENCIAL,
		NU_TELEFONE_RESIDENCIAL, NU_DDD_TELEFONE_CELULAR, NU_TELEFONE_CELULAR,
		SG_RACA_COR, ST_DEFICIENCIA, CO_TIPO_DEFICIENCIA, P_SEMESTRE_TRANSFERENCIA,
		CO_CURSO_ASSOCIADO_ADITAMENTO, VL_TAXA_JUROS_ANUAL, NU_MATRICULA, 
		VL_SEMESTRE_SEM_DESCONTO, VL_SEMESTRE_COM_DESCONTO, P_QT_SEMESTRE_CONCLUIDO, 
		VL_RENDA_PER_CAPITA, NU_PERCENTUAL_COMPROMETIMENTO, QT_MESES_FINANC_SEMESTRE_ATUAL,
		NU_PERCENT_SOLICITADO_FINANC, ST_FINANCIAR_INTEGRALIDADE_SEMESTRE,
		CO_TIPO_PERIODICIDADE, QT_PERIODICIDADE, VL_FINANCIAMENTO_EXERCICIO,
		VL_FINANCIAMENTO_GLOBAL, NOW(), P_CO_MANTENEDORA, VL_FINANCIADO_SEMESTRE,
		VL_SEMESTRE_ATUAL, VL_SALDO_AUMENTO_SEMESTRALIDADE, VL_LIMITE_GLOBAL,
		NULL, NULL, CO_MOTIVO_REJEICAO,
		DS_JUSTIFICATIVA_VALIDACAO, CO_USUARIO_INSCRICAO, ST_APROVEITAMENTO_ACADEMICO,
		NU_RIC, P_QT_SEMESTRE_FINANCIAMENTO, -- QT_SEMESTRE_FINANCIAMENTO
		NOW(), ST_PASSO_ADITAMENTO,TP_ORIGEM_FINANCIAMENTO_GLOBAL, VL_GLOBAL_FGEDUC, 
		DT_INICIO_COMPARECIMENTO_BANCO, CO_ORIGEM_DS_BAIRRO, ST_APROVACAO_ALUNO, NOW(),
		CO_CURSO_ASSOCIADO_ADITAMENTO,
		'C',
		NULL, --DT_VALIDACAO_CPSA_DESTINO
		INSCRICAO.FN_FIES_SOMA_DIAS_UTEIS(NOW, 10), --DT_LIMITE_CPSA_DESTINO
		P_DT_DESLIGAMENTO_IES, -- DT_DESLIGAMENTO 
		V_SEMESTRES_A_SEREM_CURSADOS, --QT_SEMESTRES_CURSO_DESTINO
		QT_SEMESTRES_CURSO_ORIGEM, NU_PERCENT_SOLICITADO_FINANC_ORIGINAL,
		'N', NU_CONSULTAS_RECEITA, DT_ULTIMA_CONSULTA_RECEITA,
		CO_USUARIO_SSD, ST_MIGRADO, ST_TROCA_FIANCA, CO_TIPO_FIANCA,
		ST_ALTERACAO_BOLSA_PROUNI, ST_ELEVACAO_PERC_PROUNI, ST_DIREITO_TROCA_FIANCA,
		ST_DADOS_ATUALIZADOS,
		ST_ADITAMENTO_PRELIMINAR, VL_ULTRAPASSADO_MARGEM_PRELIMINAR, VL_AUTORIZADO_AJUSTE, 
		VL_FINANCIADO_PRELIMINAR, DT_VALIDACAO_PRELIMINAR,
		CO_TIPO_PRELIMINAR, P_QT_SEMESTRE_CONCLUIDO+1, -- NU_SEMESTRE_A_CURSAR
		VL_SEMESTRALIDADE_PARA_FIES, CO_ORGAO_EXPEDIDOR, SG_UF_EXPEDIDOR, ST_ENVIA_AF
		FROM INSCRICAO.TB_FIES_ADITAMENTO
		WHERE CO_ADITAMENTO = X.CO_ADITAMENTO 
		AND CO_INSCRICAO = P_CO_INSCRICAO
		RETURNING CO_ADITAMENTO INTO V_CO_ADITAMENTO;

		INSERT INTO INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
		SELECT 
		NEXTVAL('INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITA_CO_CURSO_ASSOCIADO_ADITAMENTO_SEQ'), 
		X.NU_CPF, 
		P_CO_CURSO, -- CO_CURSO
		P_CO_TURNO, -- CO_TURNO
		P_CO_MANTENEDORA, -- CO_MANTENEDORA
		P_CO_IES, -- CO_IES
		P_CO_CAMPUS, -- CO_CAMPUS
		(SELECT SG_UF FROM VW_FIES_CURSO WHERE CO_CURSO = P_CO_CURSO AND CO_IES = P_CO_IES AND CO_CAMPUS = P_CO_CAMPUS LIMIT 1), -- SG_UF
		(SELECT CO_MUNICIPIO FROM VW_FIES_CURSO WHERE CO_CURSO = P_CO_CURSO AND CO_IES = P_CO_IES AND CO_CAMPUS = P_CO_CAMPUS LIMIT 1), -- CO_MUNICIPIO
		NOW(), CO_USUARIO_INSCRICAO,
		(P_QT_SEMESTRE_FINANCIAMENTO - P_QT_SEMESTRE_CONCLUIDO), -- QT_SEMESTRE_FINANCIAMENTO_DESTINO
		P_QT_SEMESTRE_CONCLUIDO, -- QT_SEMESTRE_ADITAMENTO_UTILIZADO
		V_CO_ADITAMENTO -- CO_ADITAMENTO
		FROM INSCRICAO.TB_FIES_CURSO_ASSOCIADO_ADITAMENTO
		WHERE CO_ADITAMENTO = X.CO_ADITAMENTO
		RETURNING CO_CURSO_ASSOCIADO_ADITAMENTO INTO V_CO_CURSO_ASSOCIADO_ADITAMENTO;

		UPDATE INSCRICAO.TB_FIES_ADITAMENTO SET 
		CO_CURSO_ASSOCIADO_ADITAMENTO = V_CO_CURSO_ASSOCIADO_ADITAMENTO 
		WHERE CO_ADITAMENTO = V_CO_ADITAMENTO;

		UPDATE INSCRICAO.TB_FIES_CURSO_ASSOCIADO SET 
		CO_MANTENEDORA     = P_CO_MANTENEDORA, 
		CO_IES             = P_CO_IES, 
		CO_CURSO           = P_CO_CURSO, 
		CO_CAMPUS          = P_CO_CAMPUS, 
		CO_TURNO           = P_CO_TURNO, 
		VL_AVALIACAO_ENADE = X.VL_AVALIACAO_ENADE
		WHERE NU_CPF = X.NU_CPF;

		UPDATE INSCRICAO.TB_FIES_TERMO_FINANCIAMENTO SET 
		QT_SEMESTRE_CONCLUIDO     = P_QT_SEMESTRE_CONCLUIDO, 
		CO_MANTENEDORA            = P_CO_MANTENEDORA, 
		QT_SEMESTRE_FINANCIAMENTO = P_QT_SEMESTRE_FINANCIAMENTO
		WHERE CO_INSCRICAO = X.CO_INSCRICAO;

		
		RAISE NOTICE '(SUCESS) ADITAMENTO DE TRANSFERENCIA INSERIDO COM SUCESSO!!!';
		COMMIT;
	ELSE 
		RAISE NOTICE 'DEU OUTRA EXCESSAO!!!';	
		ROLLBACK;

END CASE;

END LOOP;
END;

COMMIT;
RAISE NOTICE 'TRANSAÇÃO COMPLETA!!!!!!!!!!';
--TRATAMENTO DE ERRO
EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        RAISE NOTICE 'ROLLBACK APLICADO!!!!!!!!!!';
        RAISE EXCEPTION '% %', SQLERRM, SQLSTATE;
END;